Package["WolframInstitute`SyntheticInfrageometry`"]

(* EuclideanPostulates *)
FindPoint::usage = "FindPoint[graph, n] finds exactly n vertices or returns $Failed. FindPoint[graph, UpTo[n]] returns up to n. FindPoint[graph] returns one vertex. Options: \"From\" (\"Random\"|\"Center\"|\"Periphery\", a vertex, a vertex list, or origin -> dist where dist is a number, {min,max} range, or \"Max\" -- restricts the pool to vertices at that graph distance from origin), \"Distance\" (number, {min,max}, or \"Max\"), \"MaxCliques\".";
FindSegment::usage = "FindSegment[graph, p1, p2] returns the built-in single shortest path. FindSegment[graph, p1, p2, n] returns exactly n paths or $Failed; FindSegment[graph, p1, p2, UpTo[n]] returns up to n; FindSegment[graph, p1, p2, All] returns every path qualifying under the chosen method. Option Method -> \"Shortest\" (default) enumerates geodesics. Method -> \"Stretched\" enumerates paths from p1 to p2 via a constructive sweep that admits a step v_i -> w iff the recency-lex distance tuple (d(v_{i-1}, w), ..., d(v_{i-K+1}, w)) is maximal among the candidate neighbours of v_i (lookback K; the trivial entry d(v_i, w) = 1 is omitted). Method -> {\"Stretched\", \"Lookback\" -> k, \"Pruning\" -> spec, \"Constraint\" -> c} accepts k = 1 (no filter), 2 (default, no triangle shortcut), ..., All (geodesic-tight on most graphs); spec is Infinity (default), a positive integer (beam width via RandomSample), or a number 0 < p < 1 (Bernoulli keep probability with a one-element floor); c is \"Geodesic\" (default; candidate neighbours are restricted to the geodesic DAG from p1 to p2 via geodesicDAGNeighbors, paths automatically simple) or \"Free\" (candidate neighbours are the full unvisited adjacency, paths are simple but may detour). Method -> \"Pulled\" traces the rope being pulled tight from p1 toward p2 by a frontier sweep that admits a step v_i -> w iff w minimises the Forman-Ricci edge curvature F(v_i, w) among the candidate neighbours of v_i; ties branch the frontier. Method -> {\"Pulled\", \"FormanMethod\" -> \"Simple\" | \"Triangles\", \"Pruning\" -> spec, \"Constraint\" -> c} forwards FormanMethod to FormanRicciCurvature (\"Simple\" = 4 - deg u - deg v; \"Triangles\" adds 3 per shared neighbour); Pruning and Constraint match the Stretched convention. Both Stretched and Pulled stop their sweep as soon as the requested count of target-reaching paths has been collected. Method -> \"Embedding\" recurses through the geodesic DAG (or full simple-path space if \"Constraint\" -> \"Free\") and ranks the candidate paths by EmbeddingHausdorffDistance to the straight Euclidean segment p1 p2 under the graph drawing. Method -> {\"Embedding\", \"Coordinates\" -> coords, \"Constraint\" -> \"Geodesic\" | \"Free\", \"Pruning\" -> spec}: Coordinates Automatic uses GraphEmbedding[Graph[graph, GraphLayout -> \"SpringEmbedding\"]] (the closest built-in to the unit-edge-length-preserving criterion that reflects intrinsic graph geometry); Pruning matches the Stretched convention. Pipe Shortest output through CentralPaths / PeripheralPaths / EmbeddingClosestPaths to filter the bundle by a path-space metric.";
FindLine::usage = "FindLine[graph, p1, p2] returns one maximal geodesic extension through p1 and p2 or $Failed. FindLine[graph, p1, p2, n] returns exactly n or $Failed; FindLine[graph, p1, p2, UpTo[n]] returns up to n; FindLine[graph, p1, p2, All] returns all. Option \"Maximality\" controls what counts as a line -- \"Extension\" (default) keeps every triangle-equality maximal extension, \"Diameter\" keeps only those whose length equals GraphDiameter[graph]. Option Method -> \"Embedding\" reorders the result by Hausdorff distance from each line's polyline to the infinite Euclidean line through p1 and p2 under the graph drawing; suboption \"Coordinates\" -> coords overrides the default GraphEmbedding[Graph[graph, GraphLayout -> \"SpringEmbedding\"]]. Pipe through CentralPaths / PeripheralPaths / EmbeddingClosestPaths to filter the bundle by a path-space metric.";
FindShell::usage = "FindShell[graph, c, r] returns the metric shell of radius r around c -- the level surface { v : d(c, v) = r } -- as a single vertex set wrapped in a singleton list. FindShell[graph, c, r, n] returns exactly n or $Failed; FindShell[graph, c, r, UpTo[n]] returns up to n; FindShell[graph, c, r, All] returns all. Option Method: \"Metric\" (default) returns the level surface itself; \"Separating\" returns minimal connected subsets of the level surface whose removal disconnects c from { v : d(c, v) > r }; \"Embedding\" returns single-vertex sets ranked by | |coord(v) - coord(c)| - r | under the graph drawing (Constraint \"Geodesic\" restricts to the level surface, \"Free\" ranks every vertex). The cyclic case (separating cycles) is FindCircle.";
FindCircle::usage = "FindCircle[graph, c, r] returns one separating cycle in the level-surface subgraph at radius r around c, as an open vertex sequence { v0, ..., vk }, or $Failed. FindCircle[graph, c, r, n] returns exactly n or $Failed; FindCircle[graph, c, r, UpTo[n]] returns up to n; FindCircle[graph, c, r, All] returns all. The wrap-around edge { vk, v0 } is implicit. Option Method -> \"Embedding\" reorders the separating cycles by EmbeddingCircleDistance to the Euclidean circle of radius r around coord(c) under the graph drawing; suboption \"Coordinates\" -> coords overrides the default GraphEmbedding[Graph[graph, GraphLayout -> \"SpringEmbedding\"]]. Pipe through CentralCycles / PeripheralCycles / EmbeddingClosestCycles / ShortestCircumferenceCycles / LongestCircumferenceCycles to filter the bundle.";
FindParallel::usage = "FindParallel[graph, line, p] returns one line through p parallel to line, or $Failed. FindParallel[graph, line, p, n] returns exactly n or $Failed; FindParallel[graph, line, p, UpTo[n]] returns up to n; FindParallel[graph, line, p, All] returns all. A line is parallel iff every vertex on it is at distance d(p, line) from line (level-set construction: pure metric, no perpendiculars). Option Method -> \"Embedding\" reorders the parallels by Hausdorff distance to the Euclidean line through coord(p) parallel to coord(line[[1]]) -> coord(line[[-1]]); suboption \"Coordinates\" -> coords overrides the default GraphEmbedding[Graph[graph, GraphLayout -> \"SpringEmbedding\"]]. \"Spectral\" and \"Resistance\" reserved, not yet implemented.";

(* EuclideanPredicates *)
SegmentQ::usage = "SegmentQ[graph, segment] tests whether a list of vertices forms a valid geodesic segment.";
LineQ::usage = "LineQ[graph, segment] tests whether a segment is maximal -- cannot be extended to a longer geodesic.";
ShellQ::usage = "ShellQ[graph, vertexSet] tests whether vertexSet is a valid metric shell -- equidistant from some center and separating its interior from its exterior. Center and radius are derived; use FindShellParameters to obtain them.";
CircleQ::usage = "CircleQ[graph, cycle] tests whether the vertex sequence cycle = { v0, ..., vk } is a metric circle: a cyclic chain of edges in the graph whose underlying vertex set is a metric shell. Accepts both open ({v0, ..., vk}, vk != v0) and closed ({v0, ..., vk, v0}) input.";
ParallelQ::usage = "ParallelQ[graph, l1, l2] tests whether two lines are parallel (constant distance). ParallelQ[graph, l1, l2, threshold] allows distance variation up to threshold.";
SeparatesQ::usage = "SeparatesQ[graph, vertexSet, u, v] tests whether deleting vertexSet disconnects u from v. Returns False if u or v lies in vertexSet.";
FindShellParameters::usage = "FindShellParameters[graph, vertexSet] returns the list of {center, radius} pairs consistent with vertexSet being a metric shell.";
UniqueSegmentQ::usage = "UniqueSegmentQ[graph, u, v] tests whether the geodesic from u to v is unique. UniqueSegmentQ[graph] tests whether every pair of distinct vertices admits a unique geodesic (geodetic graph).";

(* EuclideanConstructions *)
FindMidpoint::usage = "FindMidpoint[graph, segment] returns the midpoint vertex of a segment (the central element). FindMidpoint[graph, p1, p2] returns one midpoint between p1 and p2 across all geodesics, or $Failed; FindMidpoint[graph, p1, p2, n] returns exactly n or $Failed; FindMidpoint[graph, p1, p2, UpTo[n]] returns up to n; FindMidpoint[graph, p1, p2, All] returns all distinct midpoints. Option Method -> \"Embedding\" returns vertices ranked by Euclidean distance to (coord(p1) + coord(p2)) / 2 under the graph drawing; Constraint \"Geodesic\" (default) restricts the pool to the metric interval { w : d(p1, w) + d(w, p2) == d(p1, p2) }, \"Free\" ranks every vertex. Suboption \"Coordinates\" -> coords overrides the default GraphEmbedding[Graph[graph, GraphLayout -> \"SpringEmbedding\"]]. \"Spectral\" and \"Resistance\" reserved, not yet implemented.";
FindPerpendicular::usage = "FindPerpendicular[graph, line, point] returns one foot of perpendicular from point to line (Euclid I.12: isosceles base midpoint), or $Failed. FindPerpendicular[graph, line, point, n] returns exactly n or $Failed; FindPerpendicular[graph, line, point, UpTo[n]] returns up to n; FindPerpendicular[graph, line, point, All] returns all feet. Option Method -> \"Embedding\" returns the line vertices ordered by Euclidean distance to the projection of coord(point) onto the affine line coord(line[[1]]) -> coord(line[[-1]]); suboption \"Coordinates\" -> coords overrides the default GraphEmbedding[Graph[graph, GraphLayout -> \"SpringEmbedding\"]]. \"Spectral\" and \"Resistance\" reserved, not yet implemented.";
FindBisectingHyperplane::usage = "FindBisectingHyperplane[graph, p1, p2] returns one inclusion-minimal subset of the bisector { v : d(p1, v) == d(p2, v) } whose removal disconnects p1 from p2 -- the graph analog of a perpendicular bisecting hyperplane. FindBisectingHyperplane[graph, p1, p2, n] returns exactly n or $Failed; UpTo[n] returns up to n; All returns every minimal hyperplane. FindBisectingHyperplane[graph, p1, p2, {lo, hi}, ...] widens the underlying bisector to vertices with lo <= d(p1, v) - d(p2, v) <= hi (use {-1, 1} to recover the parity-stranded middle pair when d(p1, p2) is odd). Accepts FindBisectingHyperplane[graph, {p1, p2}, ...] equivalently.";
CompleteEquilateralTriangle::usage = "CompleteEquilateralTriangle[graph, p1, p2] returns one vertex equidistant from p1 and p2 at distance d(p1, p2) -- the apex of an equilateral triangle on segment p1 p2 (Euclid I.1) -- or $Failed. CompleteEquilateralTriangle[graph, p1, p2, n] returns exactly n or $Failed; CompleteEquilateralTriangle[graph, p1, p2, UpTo[n]] returns up to n; CompleteEquilateralTriangle[graph, p1, p2, All] returns all such apex vertices. Option: Method (\"Metric\" (default); \"Spectral\" and \"Resistance\" reserved, not yet implemented).";
GraphAngle::usage = "GraphAngle[graph, {q1, p, q2}] deletes the open ball { v : d(p, v) < Min[d(p, q1), d(p, q2)] } and returns the shortest q1-q2 path length in the remaining graph divided by that radius. Returns Infinity when no such outside path exists.";
SegmentLineAngle::usage = "SegmentLineAngle[graph, p1, p2, line] or SegmentLineAngle[graph, segment, line] measures the distance from a segment endpoint to a line, given the other endpoint lies on the line. The name is historical -- the value is a length, not a normalized angle. Returns Infinity when the near endpoint is not on the line. Option: Method (\"Metric\" (default); \"Spectral\" reserved, not yet implemented; \"Resistance\" not applicable).";

(* PathSpace *)
CentralPaths::usage = "CentralPaths[graph, paths] keeps the paths whose maximum path-space distance to the rest of the bundle is minimal -- the metric centres of the bundle. Option Method -> \"Frechet\" (default) | \"Hausdorff\" | \"MeanFrechet\" picks the underlying base metric. Operator form CentralPaths[graph, opts][paths] is provided for piping after FindSegment / FindLine.";
PeripheralPaths::usage = "PeripheralPaths[graph, paths] keeps the paths whose maximum path-space distance to the rest of the bundle is maximal -- the eccentric paths. Same Method options as CentralPaths and the same operator form.";
EmbeddingClosestPaths::usage = "EmbeddingClosestPaths[graph, paths, {p1, p2}] keeps the paths whose drawing under GraphEmbedding is closest (in plane Hausdorff distance) to the straight Euclidean segment between p1 and p2. Operator form EmbeddingClosestPaths[graph, {p1, p2}][paths].";
CentralCycles::usage = "CentralCycles[graph, cycles] keeps the cycles whose maximum path-space distance to the rest of the bundle is minimal, with cyclic rotations factored out. Same Method options and operator form as CentralPaths.";
PeripheralCycles::usage = "PeripheralCycles[graph, cycles] keeps the cycles whose maximum path-space distance to the rest of the bundle is maximal, with cyclic rotations factored out. Same Method options and operator form as PeripheralPaths.";
EmbeddingClosestCycles::usage = "EmbeddingClosestCycles[graph, cycles, {center, radius}] keeps the cycles whose drawing under GraphEmbedding is closest (in plane Hausdorff distance) to the Euclidean circle of given centre and radius. Operator form EmbeddingClosestCycles[graph, {center, radius}][cycles].";
ShortestCircumferenceCycles::usage = "ShortestCircumferenceCycles[cycles] keeps the cycles of minimum length -- the combinatorial-girth filter. Pure list operation, no graph required.";
LongestCircumferenceCycles::usage = "LongestCircumferenceCycles[cycles] keeps the cycles of maximum length. Pure list operation, no graph required.";

(* MetricAlgebra *)
MetricInterval::usage = "MetricInterval[graph, u, v] returns the vertex set { w : d(u, w) + d(w, v) == d(u, v) } -- the union of all geodesics from u to v. The master operation of the metric algebra layer.";
GeodesicCount::usage = "GeodesicCount[graph, u, v] returns the number of distinct geodesics from u to v. Computed in polynomial time as (A^d)[u, v] where A is the adjacency matrix and d = d(u, v).";
DistanceMultiplicityMatrix::usage = "DistanceMultiplicityMatrix[graph] returns {D, M} where D is the graph distance matrix and M is the geodesic-count matrix (M[i, j] = number of geodesics from vertex i to vertex j).";
DistanceMatrixQ::usage = "DistanceMatrixQ[M] tests whether the matrix M can be the distance matrix of some graph: square, symmetric, zero on the diagonal, non-negative entries, and tropical-idempotent (the matrix form of the triangle inequality).";
MedianVertices::usage = "MedianVertices[graph, vs] returns the vertices minimising the sum of graph distances to the given vertex list vs. For a triple {a, b, c} this gives the metric median(s); a graph is a median graph iff every triple has a unique median.";

(* Coordinatization *)
FindRadarBasis::usage = "FindRadarBasis[graph, n, m] finds up to n spatial radar bases (resolving sets). m specifies which basis sizes to try: All (default), an integer (max size), {min, max}, or {exact}.";
RadarBasisQ::usage = "RadarBasisQ[graph, basis] tests whether basis is a spatial radar basis of graph (every vertex has a unique distance vector to the basis).";
RadarCoordinates::usage = "RadarCoordinates[graph, vertex, basis] returns the spatial radar coordinates of vertex: the vector of graph distances from vertex to each basis point.";
AxesCoordinates::usage = "AxesCoordinates[graph, axes, v] returns the tuple of layer indices, one per axis, of v's projection onto each axis (non-negative integers from each axis's path start). Each axis is either a vertex list (line) or a Graph (DAG). AxesCoordinates[graph, axes] returns an Association of coordinates for all graph vertices. AxesCoordinates[graph, c, v] auto-discovers orthogonal axes through c and returns the signed displacement (Z-valued) of v from c along each axis. AxesCoordinates[graph, c] returns an Association of signed coordinates for all vertices, with c at the origin. Options: Method -> \"ShortestPaths\" (default; orthogonal projection by minimum graph distance) or \"ParallelLines\" (placeholder); \"Origin\" -> vertex (signs coordinates relative to that origin when explicit axes are given).";
FindOrthogonalAxes::usage = "FindOrthogonalAxes[graph, n] returns n mutually well-separated longest paths in graph (or $Failed if fewer exist); FindOrthogonalAxes[graph, UpTo[n]] returns up to n; FindOrthogonalAxes[graph, All] returns all. FindOrthogonalAxes[graph, v, n] (or UpTo / All) constrains every axis to pass through vertex v as an interior point, anchoring a sign convention for downstream Z-valued coordinates. Options: \"DistanceFunction\" (\"MinEndpoint\" | \"Hausdorff\" | \"Separation\"), \"MinLength\" (Automatic = diameter), \"MinSeparation\" (Automatic = half the axis length), \"AxisThickness\" (axes within this Hausdorff distance of a chosen one are kept together), \"RandomPick\" (False picks the first match deterministically; True picks at random).";

(* ProjectivePostulates *)
FindPencil::usage = "FindPencil[graph, O] returns the pencil at vertex O: an Association whose keys are canonical maximal-geodesic lines through O (one per direction class) and whose values are the same vertex sets. A vertex distinct from O may appear under multiple keys when it lies on more than one maximal geodesic through O.";
PencilDirections::usage = "PencilDirections[graph, O] returns the list of canonical lines through O, one per direction class (the keys of FindPencil).";
PencilCardinality::usage = "PencilCardinality[graph, O] returns the number of distinct directions in the pencil at O.";
LineCount::usage = "LineCount[graph] returns the number of distinct canonical maximal geodesics (lines) in the graph.";
FindCommonLine::usage = "FindCommonLine[graph, vertices] returns one canonical line containing every listed vertex or $Failed. FindCommonLine[graph, vertices, n] returns exactly n or $Failed; FindCommonLine[graph, vertices, UpTo[n]] returns up to n; FindCommonLine[graph, vertices, All] returns all such lines.";
FindCommonPoint::usage = "FindCommonPoint[graph, lines] returns one vertex common to every listed line or $Failed. FindCommonPoint[graph, lines, n] returns exactly n or $Failed; FindCommonPoint[graph, lines, UpTo[n]] returns up to n; FindCommonPoint[graph, lines, All] returns all common vertices.";

(* ProjectivePredicates *)
SameDirectionQ::usage = "SameDirectionQ[graph, O, v, w] tests whether v and w lie in the same direction at O -- some maximal geodesic through O contains both.";
CollinearQ::usage = "CollinearQ[graph, vertices] tests whether all listed vertices lie on a common line.";
ConcurrentQ::usage = "ConcurrentQ[graph, lines] tests whether all listed lines share a common vertex.";
UniquePencilQ::usage = "UniquePencilQ[graph, O] tests whether every direction at O is single-valued (FindLine[graph, O, v] returns exactly one line for each v != O).";
UniqueCollinearQ::usage = "UniqueCollinearQ[graph, vertices] tests whether the listed vertices lie on a unique common line.";
WhiteheadW1Q::usage = "WhiteheadW1Q[graph] tests Whitehead axiom W1 for projective planes: every line has at least three vertices.";
WhiteheadW2Q::usage = "WhiteheadW2Q[graph] tests Whitehead axiom W2: through any two distinct vertices there is exactly one line. This is the geodetic-graph predicate.";
WhiteheadW3Q::usage = "WhiteheadW3Q[graph] tests Whitehead axiom W3: for any four distinct vertices A, B, C, D, if some line through A,B meets some line through C,D then some line through A,C meets some line through B,D. O(|V|^4) -- use on small graphs.";
ProjectivePlaneGraphQ::usage = "ProjectivePlaneGraphQ[graph] tests whether the graph is a projective plane in the synthetic-incidence sense: WhiteheadW1Q && WhiteheadW2Q && WhiteheadW3Q with non-degeneracy (some four vertices, no three collinear).";

(* TarskiPostulates *)
FindTarskiSegmentExtension::usage = "FindTarskiSegmentExtension[graph, a, b, c, d] returns one vertex x with B(a, b, x) and bx == cd -- the witness of Tarski's segment-construction axiom A4 -- or $Failed. FindTarskiSegmentExtension[graph, a, b, c, d, n] returns exactly n or $Failed; UpTo[n] returns up to n; All returns all. Generally fails on finite graphs because no vertex sits at the requested distance past b.";
FindTarskiCounterexample::usage = "FindTarskiCounterexample[graph, predQ] returns one vertex tuple witnessing the failure of the Tarski axiom predQ on graph, or $Failed. predQ is one of TarskiCongruenceIdentityQ, TarskiSegmentConstructionQ, TarskiFiveSegmentsQ, TarskiBetweennessIdentityQ, TarskiInnerPaschQ, TarskiLowerDimensionQ, TarskiUpperDimensionQ. The calling triple n / UpTo[n] / All caps the witness count. Returns $Failed for the always-True axioms and for TarskiContinuityQ (whose failure has no finite vertex-tuple witness).";

(* TarskiPredicates *)
BetweennessQ::usage = "BetweennessQ[graph, u, w, v] tests Tarski's betweenness B(u, w, v): w lies on a geodesic from u to v. Equivalently, d(u, w) + d(w, v) == d(u, v).";
EquidistanceQ::usage = "EquidistanceQ[graph, a, b, c, d] tests Tarski's equidistance ab == cd: d(a, b) == d(c, d).";
TarskiStructure::usage = "TarskiStructure[graph] returns a memoized Association bundling the hypermatrix substrate of Tarski's primitives: \"Vertices\", \"VertexIndex\", \"Distances\" (the n x n distance matrix), \"Betweenness\" (sparse rank-3 tensor B[i,j,k] = 1 iff B(v_i, v_j, v_k)), \"Equidistance\" (partition of unordered vertex pairs by distance value), \"Diameter\".";
TarskiBetweennessTensor::usage = "TarskiBetweennessTensor[graph] returns the sparse rank-3 tensor whose nonzero positions are exactly the (i, j, k) with B(v_i, v_j, v_k).";
TarskiEquidistanceClasses::usage = "TarskiEquidistanceClasses[graph] returns the partition of unordered vertex pairs by distance value -- each class is a list of {a, b} pairs with a common d(a, b).";
TarskiCongruenceReflexivityQ::usage = "TarskiCongruenceReflexivityQ[graph] tests Tarski axiom A1: for all a, b, ab == ba. Always True on undirected simple graphs.";
TarskiCongruenceTransitivityQ::usage = "TarskiCongruenceTransitivityQ[graph] tests Tarski axiom A2: ab == pq and ab == rs implies pq == rs. A tautology of equality on distance values.";
TarskiCongruenceIdentityQ::usage = "TarskiCongruenceIdentityQ[graph] tests Tarski axiom A3: ab == cc implies a == b. Holds on connected simple graphs.";
TarskiSegmentConstructionQ::usage = "TarskiSegmentConstructionQ[graph] tests Tarski axiom A4: for all a, b, c, d there is x with B(a, b, x) and bx == cd. Generally False on finite graphs.";
TarskiFiveSegmentsQ::usage = "TarskiFiveSegmentsQ[graph] tests Tarski axiom A5 (five segments): a triangle-congruence statement. Holds on median graphs; fails on graphs with non-unique geodesics in general. Brute O(n^8) with the option \"MaxTuples\" capping the search; returns Indeterminate if the cap is hit before exhaustion.";
TarskiBetweennessIdentityQ::usage = "TarskiBetweennessIdentityQ[graph] tests Tarski axiom A6: B(a, b, a) implies a == b. Always True on connected simple graphs.";
TarskiInnerPaschQ::usage = "TarskiInnerPaschQ[graph] tests Tarski axiom A7 (Inner Pasch): if B(a, p, c) and B(b, q, c), there is x in I(p, b) intersect I(q, a). Holds on median graphs (trees, hypercubes); fails on cycles >= 5 and on Petersen.";
TarskiLowerDimensionQ::usage = "TarskiLowerDimensionQ[graph] tests Tarski axiom A8: there exist three non-collinear points. Uses the projective CollinearQ (maximal-geodesic version).";
TarskiUpperDimensionQ::usage = "TarskiUpperDimensionQ[graph] tests Tarski axiom A9: three points equidistant from two distinct points are collinear. False on graphs of effective dimension >= 3 (hypercubes, 3D grids).";
TarskiEuclidAxiomQ::usage = "TarskiEuclidAxiomQ[graph] tests Tarski axiom A10 (Euclid's parallel-axiom variant). Iteration-1 stub: returns Indeterminate and emits TarskiEuclidAxiomQ::nyi.";
TarskiContinuityQ::usage = "TarskiContinuityQ[graph] tests Tarski axiom A11 (first-order Dedekind continuity schema). Always False on finite discrete graphs -- the failure is structural and has no finite vertex-tuple witness.";
TarskiAxiomQ::usage = "TarskiAxiomQ[graph] returns an Association keyed by descriptive axiom names with the per-axiom result, composing all eleven Tarski*Q predicates into a dashboard.";

(* TarskiConstructions *)
FindTarskiReflection::usage = "FindTarskiReflection[graph, x, a] returns one vertex x' with B(x, a, x') and ax == ax' -- the reflection of x through a in Tarski's primitives. FindTarskiReflection[graph, x, a, n] returns exactly n or $Failed; UpTo[n] returns up to n; All returns all candidates.";
FindTarskiMidpoint::usage = "FindTarskiMidpoint[graph, a, b] returns one vertex m with B(a, m, b) and am == mb -- the synthetic midpoint defined only from B and E. FindTarskiMidpoint[graph, a, b, n] returns exactly n or $Failed; UpTo[n] returns up to n; All returns all. Returns { } when no synthetic midpoint exists (e.g. odd-distance pairs); contrast FindMidpoint, which always returns a central interval element.";

(* TropicalPostulates *)
FindTropicalSegment::usage = "FindTropicalSegment[graph, u, v] returns one tropical segment from u to v as a sorted vertex set, or $Failed. FindTropicalSegment[graph, u, v, n] returns exactly n or $Failed; FindTropicalSegment[graph, u, v, UpTo[n]] returns up to n; FindTropicalSegment[graph, u, v, All] returns all. In the pure-metric reading each tropical segment is the vertex set of a graph geodesic.";
FindGeodesicConvexHull::usage = "FindGeodesicConvexHull[graph, S] returns the smallest superset of S closed under FindSegment, as a sorted vertex list.";

(* TropicalPredicates *)
TropicalSegmentQ::usage = "TropicalSegmentQ[graph, S, u, v] tests whether the vertex set S realises a tropical segment from u to v.";
GeodesicallyConvexQ::usage = "GeodesicallyConvexQ[graph, S] tests whether the vertex set S is closed under FindSegment.";
UniqueTropicalSegmentQ::usage = "UniqueTropicalSegmentQ[graph, u, v] tests whether the tropical segment from u to v is single-valued.";
TropicalT1Q::usage = "TropicalT1Q[graph] tests tropical axiom T1: every two vertices admit a tropical segment. Equivalent to ConnectedGraphQ in the pure-metric reading.";

(* Enumeration *)
EnumerateGraphs::usage = "EnumerateGraphs[n, predQ] returns all connected n-vertex graphs (from GraphData[\"Connected\", n], canonically sorted) for which predQ[graph] is True. EnumerateGraphs[n, predQ, k] returns exactly k or $Failed; EnumerateGraphs[n, predQ, UpTo[k]] returns up to k; EnumerateGraphs[n, predQ, All] returns all. Option: \"From\" -> graphList overrides the default GraphData generator with a user-supplied list (n is then ignored).";

(* Tessellations *)
TorusTessellation::usage = "TorusTessellation[{n, m}, p] glues copies of CycleGraph[p] into a torus graph along the rectangular fundamental-domain grid {n, m}. The polygon size p must be 3, 4, or 6 -- the only integer solutions of the flat-torus Euler relation 1/p + 1/q = 1/2 with q = 2 p / (p - 2) the vertex valency of the regular {p, q} tessellation. Counts: p = 3 (triangles) gives V = n m, E = 3 n m, F = 2 n m, valency 6; p = 4 (squares) gives V = n m, E = 2 n m, F = n m, valency 4; p = 6 (hexagons) gives V = 2 n m, E = 3 n m, F = n m, valency 3. Other p are rejected with TorusTessellation::badp -- pentagons, heptagons and the like need the (placeholder) SchlafliTessellation generator. TorusTessellation[n, p] is shorthand for {n, n}.";
SchlafliTessellation::usage = "SchlafliTessellation[{p, q}, ...] is a placeholder for the general regular gluing of CycleGraph[p] copies into a graph in which q polygons meet at each vertex, for any Schlafli pair {p, q}: spherical (Platonic solids), Euclidean (forwards to TorusTessellation), or hyperbolic (finite-index torsion-free quotients of the {p, q} triangle group). Not yet implemented; see Wiki/Plans/SchlafliGluings.md.";

(* Scenes *)
InfraScene::usage = "InfraScene[objects, hypotheses] constructs a scene descriptor from symbolic objects and hypotheses (constructions and assertions). Access properties via scene[\"Steps\"], scene[\"Constructions\"], scene[\"Assertions\"], scene[\"DependencyGraph\"].";
FindInfraScene::usage = "FindInfraScene[scene, graph] evaluates all construction steps and returns a list of InfraInstance objects. FindInfraScene[scene, graph, n] evaluates up to n steps. FindInfraScene[scene, graph, <|p -> v, ...|>] starts with pre-fixed bindings. FindInfraScene[scene, graph, n, <|...|>] combines both. Option: \"PruningProbability\" (default 0).";
InfraInstance::usage = "InfraInstance[bindings] wraps a solved binding association from FindInfraScene. Access bindings via instance[[1]][symbol].";
InfraGeometricStep::usage = "InfraGeometricStep[{hyp1, hyp2, ...}] groups hypotheses into a manual construction step. InfraGeometricStep[{hyps...}, \"label\"] adds a label. When used in InfraScene, steps follow the given order instead of auto-computed dependency levels. Points from earlier steps are treated as fixed when later steps execute.";
InfraPoint::usage = "InfraPoint[] represents any vertex. InfraPoint[v] fixes a vertex. InfraPoint[\"Center\"] or InfraPoint[\"Periphery\"] selects from graph center/periphery. InfraPoint[origin, dist] selects vertices at given distance. InfraPoint[n] finds n mutually distant vertices. The single-List-arg form InfraPoint[{v1, v2, ...}] doubles as a multi-object wrapper for InfraSceneHighlight (forces point semantics: vertices highlighted, no edges).";
InfraSegment::usage = "InfraSegment[p, q] represents geodesics between p and q. Used in InfraScene hypotheses. The single-List-arg form InfraSegment[{seg1, seg2, ...}] doubles as a multi-object wrapper for InfraSceneHighlight (forces sequential-edge semantics via Partition[path, 2, 1]).";
InfraLine::usage = "InfraLine[p, q] represents maximal geodesic extensions through p and q. InfraLine[path] extends a given path. Used in InfraScene hypotheses. The single-List-of-paths form InfraLine[{line1, line2, ...}] doubles as a multi-object wrapper for InfraSceneHighlight (forces sequential-edge semantics, same as InfraSegment[...]).";
InfraShell::usage = "InfraShell[center, radius] represents metric shells at given radius from center -- the level surface { v : d(center, v) = radius }. Used in InfraScene hypotheses. The single-List-arg form InfraShell[{set1, set2, ...}] doubles as a multi-object wrapper for InfraSceneHighlight (forces induced-subgraph semantics: edges = EdgeList[Subgraph[g, set]]).";
InfraCircle::usage = "InfraCircle[center, radius] represents metric circles at given radius from center -- separating cycles in the level-surface subgraph. Used in InfraScene hypotheses. The single-List-arg form InfraCircle[{cyc1, cyc2, ...}] doubles as a multi-object wrapper for InfraSceneHighlight (forces sequential-edge semantics with auto-closure: edges = Partition[Append[cyc, First @ cyc], 2, 1]).";
InfraIntersection::usage = "InfraIntersection[obj1, obj2] represents the vertex set intersection of two geometric objects. Used in InfraScene hypotheses.";
InfraDistance::usage = "InfraDistance[p, q] represents graph distance between p and q. Used in InfraScene assertions.";
InfraSegmentQ::usage = "InfraSegmentQ[s] asserts that s is a valid geodesic segment. Used in InfraScene assertions.";
InfraShellQ::usage = "InfraShellQ[vs] asserts that vs is a valid metric shell. Used in InfraScene assertions.";
InfraCircleQ::usage = "InfraCircleQ[c] asserts that c is a valid metric circle (separating cycle). Used in InfraScene assertions.";
InfraLineQ::usage = "InfraLineQ[s] asserts that s is a maximal geodesic. Used in InfraScene assertions.";
InfraParallelQ::usage = "InfraParallelQ[l1, l2] asserts that two lines are parallel. Used in InfraScene assertions.";
InfraIntersectQ::usage = "InfraIntersectQ[s1, s2] asserts that two sets intersect. Used in InfraScene assertions.";

(* Interactive Viewers *)
InfraSceneViewer::usage = "InfraSceneViewer[scene, graph] creates an interactive visualization of an InfraScene on a graph. InfraSceneViewer[scene, graph, <|p -> v, ...|>] starts with pre-fixed bindings. A step slider controls the current construction step, \"Fix & advance\" pins the current instance and moves to the next step, and \"Reset\" clears all fixed bindings. Aggregate mode shows branch frequency; single-instance mode browses individual instances.";

(* Viewers *)
InfraSceneHighlight::usage = "InfraSceneHighlight[g, multiObjects] renders a list of multi-objects diffusely on a graph. By default each entry is auto-classified per representation: a value matching VertexList[g] is a single vertex (point); anything else is a list of vertices (induced subgraph). Use the explicit single-List-arg wrappers when auto-classification is ambiguous: InfraPoint[reps] forces point semantics, InfraSegment[reps] (or InfraLine[reps]) forces sequential-edge semantics, InfraShell[reps] forces induced-subgraph semantics, InfraCircle[reps] forces sequential edges with auto-closure. These are the same heads used by InfraScene; the arg shape distinguishes the two layers. Within one multi-object, vertex/edge intensity scales with how many representations pass through; across multi-objects, colors blend on shared vertices/edges. Default colour is by head: InfraPoint -> $InfraPointColor, InfraSegment/InfraLine -> $InfraSegmentColor, InfraShell -> $InfraShellColor, InfraCircle -> $InfraCircleColor; unwrapped entries fall through to a cycling palette indexed by position. Wrap as `entry -> color` to override. Options \"OpacityRange\", \"ThicknessRange\", \"PointSizeRange\" tune the diffusion envelope.";
PointViewer::usage = "PointViewer[g] creates an interactive viewer for selecting points in a graph. Controls: Points slider, From (Random/Center/Periphery), Separation (None/Max). PointViewer[g, sym] stores the current selection in sym.";
SegmentViewer::usage = "SegmentViewer[g] creates an interactive visualization for exploring geodesic segments between points in a graph.";
ShellViewer::usage = "ShellViewer[g] creates an interactive visualization for exploring metric shells centered at a point in a graph. Method setter chooses between \"Metric\" (level surface) and \"Separating\" (minimal connected separators).";
CircleViewer::usage = "CircleViewer[g] creates an interactive visualization for exploring separating cycles centered at a point in a graph.";

(* Curvatures *)
FormanRicciCurvature::usage = "FormanRicciCurvature[graph] returns Association[edge -> kappa] with the discrete Forman-Ricci curvature of every edge. Method -> \"Simple\" (default) gives F(e) = 4 - deg(u) - deg(v) (1-skeleton Forman with all weights 1). Method -> \"Triangles\" gives F(e) = 4 - deg(u) - deg(v) + 3 #triangles(e), the 2-complex form where every 3-cycle is filled as a 2-cell.";
OllivierRicciCurvature::usage = "OllivierRicciCurvature[graph] returns Association[edge -> kappa] with the Ollivier-Ricci curvature kappa(u, v) = 1 - W_1(mu_u, mu_v) / d(u, v) of every edge, where mu_x is uniform on the open neighborhood N(x) and W_1 is the Wasserstein-1 distance under graph distance (idleness alpha = 0).";
WolframRicciScalar::usage = "WolframRicciScalar[graph, v] returns Association[r -> R(r)] with the volume-comparison Ricci scalar R(r) = 6(d+2)/r^2 (1 - V(r)/V_E(d, r)) at vertex v, where V(r) = |B_r(v)| and V_E(d, r) = pi^(d/2) r^d / Gamma[d/2 + 1]. WolframRicciScalar[graph, v, {rmin, rmax}] restricts the radius range. WolframRicciScalar[graph, All, ...] returns Association[vertex -> Association[r -> R(r)]]. Option \"Dimension\" -> Automatic (default) reads the local dimension off the log-difference (Log V(r+1) - Log V(r)) / (Log(r+1) - Log r) at each radius (the default range is then capped at eccentricity(v) - 1 since r+1 must be available). \"Dimension\" -> d uses a fixed numeric dimension and lets the range run up to eccentricity(v).";
