Package["WolframInstitute`SyntheticInfrageometry`"]

(* Usage messages: one sentence per signature; options listed by name only.
   Full method/sub-option trees and worked examples live in the guides
   and tutorials, not here. See CLAUDE.md "Usage messages" for the rules. *)

(* ===================== InfraPoint ===================== *)

InfraPoint::usage = "InfraPoint[{v1, ..., vk}] is the unweighted multi-realisation form (each vertex mass 1); InfraPoint[{v1, ...}, {w1, ...}] carries explicit per-vertex mass. The canonical form has a duplicate-free support with positive masses that add on aggregation; an all-ones weighted form collapses to the bare 1-arg form. Accessors [\"Support\"], [\"Weights\"], [\"Mass\"], [\"First\"]. Find* finders return a List of unary InfraPoint[{v}] wrappers; wrap with InfraPoint @ ... to collapse via auto-flatten (masses add). Scene-language variants InfraPoint[] / InfraPoint[\"Center\"] / InfraPoint[\"Periphery\"] / InfraPoint[origin, dist] / InfraPoint[n] are constructors used inside InfraScene. In InfraSceneHighlight a weighted InfraPoint renders as a mass heat-map (heaviest vertex brightest).";
FindInfraPoint::usage = "FindInfraPoint[graph] returns one vertex as {InfraPoint[{v}]}. FindInfraPoint[graph, n] returns a List of n unary InfraPoint[{v}] wrappers or $Failed; UpTo[n] returns up to n; All returns every vertex. Options: \"From\", \"Distance\" (d for exactly distance d; {dMin, dMax} for a range, Infinity allowed in dMax), \"MaxCliques\".";
FindInfraMidpoint::usage = "FindInfraMidpoint[graph, InfraSegment[{walks}]] returns one InfraPoint: the vertices at the index/indices closest to each walk's centre (n+1)/2, unioned over the walks (a single vertex when d(p1, p2) is even, a two-vertex mesopoint when odd). FindInfraMidpoint[graph, walk] is the bare-walk shortcut. FindInfraMidpoint[graph, p1, p2] unions over every geodesic. Options: Method (\"Metric\" (default) | \"Embedding\" (single nearest vertex to the coord-space midpoint, with sub-options \"Coordinates\" and \"Pool\")), \"Tolerance\" (0 (default); widens the band beyond the closest index by that many graph-distance units).";
FindInfraGoldenSection::usage = "FindInfraGoldenSection[graph, InfraSegment[{walks}]] returns one InfraPoint: the vertex at the index closest to each walk's golden index 1 + (n-1)/GoldenRatio (AS == AB/phi), unioned over the walks; the golden index is irrational, so it is a single point per walk. FindInfraGoldenSection[graph, walk] is the bare-walk shortcut. FindInfraGoldenSection[graph, p1, p2] unions over every geodesic. Options: Method (\"Metric\" (default) | \"Embedding\" (single nearest vertex to the coord-space point A + (1/GoldenRatio)(B - A), with sub-options \"Coordinates\" and \"Pool\")), \"Tolerance\" (0 (default); widens the band beyond the closest index by that many graph-distance units).";
FindInfraReflection::usage = "FindInfraReflection[graph, x, a] returns a List of unary InfraPoint[{x'}] reflections of x through a, where x' satisfies B(x, a, x') and ax == ax'. With n / UpTo[n] / All controls multiplicity.";
CompleteInfraEquilateralTriangle::usage = "CompleteInfraEquilateralTriangle[graph, p1, p2] returns a List of unary InfraPoint[{c}] apex vertices equidistant from p1 and p2 at distance d(p1, p2) (Euclid I.1). With n / UpTo[n] / All controls multiplicity. Option: Method (\"Metric\" (default)).";
FindInfraCommonPoint::usage = "FindInfraCommonPoint[graph, lines] returns a List of unary InfraPoint[{v}] wrappers for the vertices on every listed line, or $Failed. With n / UpTo[n] / All controls multiplicity. Entries may be bare vertex sequences or InfraSegment / InfraRay wrappers.";
FindClosestInfraPoint::usage = "FindClosestInfraPoint[graph, line, point] returns a List of unary InfraPoint[{v}] wrappers for the vertices on line at minimum graph distance from point (metric argmin). FindClosestInfraPoint[graph, line, point, n] / UpTo[n] / All controls multiplicity. line accepts a bare vertex sequence or InfraSegment / InfraLine / InfraPath / InfraRay wrapper; point accepts a bare vertex or InfraPoint[{...}]; multi-realisation wrappers spread Cartesian. Distinct from FindInfraPerpendicular, which runs the synthetic Euclid I.12 foot construction.";
SelectInfraPoint::usage = "SelectInfraPoint[graph, vertices] returns one vertex drawn from the bundle treated as a finite metric space under graph distance. SelectInfraPoint[graph, vertices, n] returns exactly n unary InfraPoint[{v}] wrappers or $Failed; UpTo[n] returns up to n; All returns the whole filtered pool. Options mirror FindInfraPoint: \"From\" (All (default), \"Center\", \"Periphery\", anchor -> spec, InfraPoint[{...}] -> spec, vertex, list), \"Distance\" (None (default), \"Max\", d, {dMin, dMax}), \"MaxCliques\". Accepts InfraPoint[{...}] or any set-like Infra* wrapper (InfraBall, InfraShell, InfraSet, ...) as the bundle. Operator form SelectInfraPoint[graph, n, opts][vertices].";
InfraReachableQ::usage = "InfraReachableQ[graph, p1, p2] tests whether some realisation of p1 lies in the same connected component as some realisation of p2. Accepts InfraPoint[{...}], a bare vertex, or a list of vertices.";

(* ===================== InfraSegment ===================== *)

InfraSegment::usage = "InfraSegment[{path}] is the unary form (one geodesic path); InfraSegment[{path1, ..., pathk}] is the multi-realisation form. Single-index seg[[i]] returns the weighted InfraPoint of the i-th position across realisations (mass = multiplicity; i may be negative); First[seg] and multi-index seg[[1,1]] keep the realisation-list / first-path meaning. Find* finders return a List of unary InfraSegment[{path}] wrappers; wrap that list with InfraSegment @ ... to collapse to multi via auto-flatten. Scene-language constructor InfraSegment[p, q] is used inside InfraScene. The multi form is consumed by InfraSceneHighlight (sequential-edge semantics).";
FindInfraSegment::usage = "FindInfraSegment[graph, p1, p2] returns {InfraSegment[{path}]} for one geodesic between p1 and p2 (shortest path; geodesic-ness implicit). FindInfraSegment[graph, p1, p2, n] / UpTo[n] / All returns up to n unary InfraSegment[{path}] wrappers. Endpoints accept InfraPoint[{...}] for multi-anchor spread. Options: Properties (AND-conjoined filters on the geodesic bundle; supported: {\"EdgeMin\", f}, {\"EdgeMax\", f} with user-supplied edge function f[a, b], and {\"LongestPath\", \"Window\" -> k, \"Aggregation\" -> \"Lex\" | \"Sum\"}; \"ShortestPath\" is implicit and not a valid Property), Method (\"Exhaustive\" (default), {\"Exhaustive\", \"Pruning\" -> spec}, \"Greedy\").";
ExtendInfraSegment::usage = "ExtendInfraSegment[graph, a, b, c, d] returns InfraPoint[{x}] for x with B(a, b, x) and d(b, x) == d(c, d) (Tarski axiom A4 synthetic-extension). ExtendInfraSegment[graph, a, b, c, d, n] / UpTo[n] / All controls multiplicity. The 2-arg ExtendInfraSegment[graph, segment] form (extend segment to a maximal line) has been removed; use FindInfraLine[graph, segment] for the geodesic case or ExtendInfraPath[graph, segment, All, Properties -> {\"Simple\", {\"ShortestPath\"}}] for per-step extension.";
InfraPathQ::usage = "InfraPathQ[graph, walk] tests whether walk is a simple path in graph (consecutive adjacency and no repeated vertices). Hierarchy: InfraPathQ \[Superset] InfraSegmentQ \[Superset] InfraLineQ.";
InfraPath::usage = "InfraPath[{walk}] is the unary form (one walk, possibly non-simple); InfraPath[{walk1, ..., walkk}] is the multi-realisation form. Inside InfraScene, InfraPath[p1, p2, ..., pk] is the step-wise scene-DSL constructor: every length-(k-1) walk {v1, ..., vk} with vi in pi and each consecutive pair (vi, v_{i+1}) a graph edge (non-simple chains kept). FindInfraPath finders return a List of unary InfraPath[{walk}] wrappers; wrap that list with InfraPath @ ... to collapse to multi via auto-flatten. Rendered like InfraSegment (sequential-edge semantics).";
FindInfraPath::usage = "FindInfraPath[graph, p1, p2] returns {InfraPath[{walk}]} for one walk between p1 and p2 (default Properties -> {} allows non-simple walks). FindInfraPath[graph, p1, p2, kspec] restricts walk length: kspec is k (length <= k), {k} (length == k), {kmin, kmax} (range), or Infinity (any length, default). FindInfraPath[graph, p1, p2, kspec, n] / UpTo[n] / All controls multiplicity. Endpoints accept InfraPoint[{...}] for multi-anchor spread. Options: Properties (AND-conjoined list of per-step constraints; supported: \"Simple\", {\"ShortestPath\", \"Window\" -> k}, {\"LongestPath\", \"Window\" -> k, \"Aggregation\" -> \"Lex\" | \"Sum\"}, {\"EdgeMin\", f}, {\"EdgeMax\", f}), Method (\"Exhaustive\" (default), {\"Exhaustive\", \"Pruning\" -> spec}).";
ExtendInfraPath::usage = "ExtendInfraPath[graph, path] extends a walk by a per-step geometric rule until inextensible and returns a List of unary InfraPath[{walk}] wrappers. ExtendInfraPath[graph, path, n] / UpTo[n] / All controls multiplicity; the multi-realisation InfraPath wrapper spreads. Options: Properties (same per-step constraints as FindInfraPath; default {} allows non-simple extensions), Method (\"Exhaustive\" (default), {\"Exhaustive\", \"Pruning\" -> spec}), \"Length\" (Automatic (default; extend until inextensible) or integer step budget), \"Direction\" (\"BothSides\" (default; per-step symmetric -- each step adds at most one vertex on each side, a side freezes when stuck while the other keeps growing), \"Forward\", \"Backward\").";
ConcatenateInfraPath::usage = "ConcatenateInfraPath[path1, path2] returns a List of unary InfraPath[{walk}] wrappers for every compatible pair (walk1 from path1, walk2 from path2) with Last[walk1] === First[walk2], concatenated as Join[walk1, Rest[walk2]]. ConcatenateInfraPath[path1, path2, n] / UpTo[n] / All controls multiplicity (default All). Both arguments accept multi-realisation InfraPath[{...}] wrappers or lists of unary wrappers.";
InfraLoop::usage = "InfraLoop[{walk}] is the unary form (one closed walk, First === Last); InfraLoop[{walk1, ..., walkk}] is the multi-realisation form. Open-walk realisations are auto-closed by appending First. Inside InfraScene, InfraLoop[v1, v2, ..., vk] is the scene-DSL constructor (auto-closes if needed). Used by the polymorphic homotopy finders as the base-pointed loop wrapper (homotopy fixes the base vertex unless \"FreeHomotopy\" -> True).";
InfraString::usage = "InfraString[{walk}] is the unary form (one closed walk modulo cyclic rotation); InfraString[{walk1, ..., walkk}] is the multi-realisation form. Each realisation is stored as the lex-least cyclic rotation of Most[closeWalk[walk]] (the open canonical form, without the wrap-around vertex repetition); orientation is preserved. Equality between strings is SameQ on canonical forms. Inside InfraScene, InfraString[v1, v2, ..., vk] is the scene-DSL constructor (auto-closes and canonicalises). Used by the polymorphic homotopy finders as the free-loop wrapper (no base point; cyclic rotations are identified).";
InfraSegmentQ::usage = "InfraSegmentQ[graph, segment] tests whether segment is a geodesic path.";
UniqueInfraSegmentQ::usage = "UniqueInfraSegmentQ[graph, u, v] tests whether the geodesic from u to v is unique. UniqueInfraSegmentQ[graph] tests the geodetic property (every pair has a unique geodesic).";

(* ===================== InfraLine ===================== *)

InfraLine::usage = "InfraLine[{line}] is the unary form (one maximal geodesic); InfraLine[{line1, ..., linek}] is the multi-realisation form. Single-index line[[i]] returns the weighted InfraPoint of the i-th position across realisations (mass = multiplicity; i may be negative); First[line] and multi-index line[[1,1]] keep the realisation-list / first-line meaning. FindInfraLine / FindInfraParallel / FindInfraCommonLine return a List of unary InfraLine[{line}] wrappers; wrap with InfraLine @ ... to collapse via auto-flatten. Scene-language constructor InfraLine[p, q] is used inside InfraScene. Rendered like InfraSegment (sequential-edge semantics).";
FindInfraLine::usage = "FindInfraLine[graph, p1, p2] returns {InfraLine[{line}]} for one maximal geodesic line through p1 and p2. FindInfraLine[graph, segment] returns maximal geodesic lines containing segment as a contiguous sub-sequence. FindInfraLine[graph, ..., n] / UpTo[n] / All controls multiplicity. Options: Properties ({} only at present; raises ::badproperty otherwise), Method (\"Exhaustive\" (default; joint-maximal enumeration via findLineExtensions), {\"Exhaustive\", \"Pruning\" -> spec}, \"Greedy\" (DFS one realisation, walks outward from each endpoint until inextensible)), \"Maximality\" (\"Extension\" (default) | \"Diameter\"), \"Direction\" (\"BothSides\" (default; extend the middle on both sides), \"Forward\" (extend only past the right end, First[segment]/p1 fixed as line start), \"Backward\" (extend only past the left end, Last[segment]/p2 fixed as line end)).";
FindInfraParallel::usage = "FindInfraParallel[graph, line, p] returns a List of unary InfraLine[{line}] wrappers for parallels through p (parallel = constant distance to line), or $Failed. FindInfraParallel[graph, line, p, n] / UpTo[n] / All controls multiplicity. Options: Properties ({} only at present), Method (\"Exhaustive\" (default), {\"Exhaustive\", \"Pruning\" -> spec}, \"Greedy\").";
FindInfraPerpendicular::usage = "FindInfraPerpendicular[graph, line, point] returns a List of InfraLine realisations through point perpendicular to line. FindInfraPerpendicular[graph, line, point, n] / UpTo[n] / All controls multiplicity. Options: Method (\"Metric\" (default; foot-of-perp via Euclid I.12), \"Projection\", \"Coordinate\", \"Arclength\", \"Alexandrov\", or any of these with sub-options inside the Method spec, e.g. {\"Alexandrov\", \"Curvature\" -> k, \"Tolerance\" -> t}, {\"Coordinate\", \"ZeroTest\" -> \"Mean\" | \"Median\" | \"Contains\" | {name, \"Tolerance\" -> t} | f}, {\"Projection\", \"Equality\" -> \"Subset\" | \"Set\" | \"Multiset\" | \"Diffuse\" | \"Overlap\"} -- forwarded verbatim to InfraPerpendicularQ); \"Radius\" -> All (default) | r_Integer localises construction and test to NeighborhoodGraph[g, point, r].";
FindInfraCommonLine::usage = "FindInfraCommonLine[graph, vertices] returns a List of unary InfraLine[{line}] wrappers for the canonical lines containing every listed vertex, or $Failed. With n / UpTo[n] / All controls multiplicity. Entries may be bare vertices or InfraPoint / InfraSegment / InfraLine / InfraRay wrappers.";
InfraLineQ::usage = "InfraLineQ[graph, segment] tests whether segment is a maximal geodesic.";
InfraParallelQ::usage = "InfraParallelQ[graph, l1, l2] tests whether two lines are parallel (constant distance). InfraParallelQ[graph, l1, l2, threshold] allows distance variation up to threshold.";
InfraPerpendicularQ::usage = "InfraPerpendicularQ[graph, l1, l2] tests whether two lines are perpendicular at every common vertex; returns False on empty intersection. Option Method carries the test family and its sub-options inside the spec: \"Projection\" (default; foot-of-perp projection of each line onto the other compared to the intersection set) with sub-option \"Equality\" (\"Subset\" default, \"Set\" / \"Multiset\" / \"Diffuse\" / \"Overlap\" forwarded to InfraEqualQ); \"Arclength\" / \"Alexandrov\" / {\"Alexandrov\", \"Curvature\" -> k} (four corner-wedge angles InfraAngle[..., Method -> mtd] equal within sub-option \"Tolerance\", radians); \"Coordinate\" (project each non-common vertex onto the other line via FindClosestInfraPoint and decide whether the resulting signed-coordinate cloud is at 0 via sub-option \"ZeroTest\" -- bare \"Mean\" (default) / \"Median\" / \"Contains\" use Tolerance 0; the nested form {name, \"Tolerance\" -> t} carries its own tolerance; \"Mean\" / \"Median\" test Abs[stat[c]] <= Tolerance, \"Contains\" tests Min[c] - tol <= 0 <= Max[c] + tol; or a user predicate function f called directly on the coordinate list). Top-level option \"Radius\" -> All (default) | k_Integer restricts each test to the k-neighborhood of the common vertex.";
PencilDirections::usage = "PencilDirections[graph, O] returns the canonical maximal geodesics through O, one per projective direction class at O.";
PencilCardinality::usage = "PencilCardinality[graph, O] returns the number of distinct direction classes at O.";
LineCount::usage = "LineCount[graph] returns the number of distinct canonical maximal geodesics in graph.";
FindLineHull::usage = "FindLineHull[graph, S] returns the smallest superset of S closed under the line operator (the maximal geodesics through each pair), as an InfraSet. S is any Infra* object, a list of them, or a bare vertex list. Option \"LineStructure\" (None (default), or an InfraLineStructure / list of lines) closes under that fixed line family instead of all maximal geodesics.";
LineHullQ::usage = "LineHullQ[graph, S] returns True if S is closed under the line operator, i.e. equals its own FindLineHull. Option \"LineStructure\" as in FindLineHull.";
UniversalLineQ::usage = "UniversalLineQ[graph] returns True if some pair of vertices spans a line filling a whole connected component (Chen-Chvatal). UniversalLineQ[graph, {u, v}] tests the single line through u, v.";

(* ===================== InfraLineStructure ===================== *)

InfraLineStructure::usage = "InfraLineStructure[{line1, ..., linek}] is a consistent geodesic path system, stored as its maximal lines (the structure's realisations). Accessors: [\"Lines\"] / [\"Realizations\"] the maximal lines, [\"First\"] / [[i]] one line, [\"Length\"] per-line edge counts; [\"Paths\"] the unfolded association <|{u,v} -> P(u,v)|>, [\"Incidence\"] the transpose <|v -> {line numbers}|>, [\"Coordinates\"] <|v -> {{line, offset}}|> (offset = edges from the line start), and [\"Path\", u, v] recovers P(u,v) oriented u -> v.";

FindLineStructure::usage = "FindLineStructure[graph] returns an InfraLineStructure[{lines}]: a consistent (subpath-closed) geodesic path system -- one shortest path per pair, with every stretch of a chosen path again the chosen path -- stored as its maximal lines. Option Method (\"Lexicographic\" (default; exact 1 + 2^(-rank) weighting, edges ranked by sorted endpoints) | {\"Random\", seed} | \"Resistance\" | \"Weight\" -> w) supplies the edge ranking that breaks geodesic ties; every method yields a consistent system. See InfraLineStructure for accessors.";

ConsistentPathSystemQ::usage = "ConsistentPathSystemQ[graph, obj] tests whether a geodesic path system is subpath-closed (Cizma-Linial consistent). obj is an InfraLineStructure, a list of lines, or an association <|{u,v} -> path|>.";

(* ===================== InfraShell ===================== *)

InfraShell::usage = "InfraShell[{set}] is the unary form (one metric shell vertex set); InfraShell[{set1, ..., setk}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraShell @ ... to collapse to multi via auto-flatten. Scene-language constructor InfraShell[center, radius] is used inside InfraScene. The multi form is consumed by InfraSceneHighlight (induced-subgraph semantics).";
FindInfraShell::usage = "FindInfraShell[graph, c, r] returns {InfraShell[{levelSet}]} for the metric shell { v : d(c, v) == r }; r may be {rmin, rmax} for a tolerance band. FindInfraShell[graph, c, r, n] returns a List of n unary InfraShell[{set}] wrappers or $Failed; UpTo[n] returns up to n; All returns all. Options: Properties (list of \"Separating\" / \"Connected\"; AND-conjoined filter on candidate subsets; empty default returns the level set itself), Method (\"Exhaustive\" (default; BFS over the peel-DAG, accepts nested {\"Exhaustive\", \"Pruning\" -> spec}) | \"Greedy\" (DFS, one realisation); ignored when Properties is empty).";
FindInfraOsculatingShell::usage = "FindInfraOsculatingShell[graph, path, i, k] returns InfraShell[{set}] for the smallest-radius osculating shell at the k-vertex window centered on path[[i]]: the level set { v : d(c, v) == r } around an osculating center c equidistant from every window-vertex with common distance r. FindInfraOsculatingShell[graph, path, i, k, n] returns up to n shells sorted by ascending radius (one shell per osculating center), with UpTo[n] / All for the full calling triple. path may be a vertex list or an InfraPath wrapper (multi-realisation paths are spread and unioned). Forwards Properties / Method options to FindInfraShell.";
FindAdvancingInfraFront::usage = "FindAdvancingInfraFront[graph, origin, steps] returns the foliation { InfraSet[S_0], ..., InfraSet[S_steps] } of an advancing oriented wavefront from origin. The state is a set of geodesic walk-tails (...,a,b); the head b advances to b -> c and S_i is the set of heads. The default front is non-backtracking (c in N(b) minus {a}), so it never empties and propagates indefinitely (the wave circulates) -- on a triangle {A},{B,C},{B,C},{A},... -- unlike the metric-sphere shell which dies. Option \"SelfAvoidanceDepth\" -> n (default 1): c may not be any of the last n tail vertices; n = 1 is non-backtracking, larger n forbids closing cycles of length <= n+1 (n = 2 makes a triangle die at step 3), n = Infinity is fully self-avoiding. Option \"GeodesicSprayDepth\" -> None (default) | k_Integer | Infinity: forbid steps transverse in the geodesic spray of a reference vertex (d(p,c) == d(p,b)); k uses the k-th predecessor (a local moving frame, delays surface flooding), Infinity uses the origin (a global frame, the wave stays a band and never floods). origin is a single vertex (bare label, including a list-vertex {i,j}); an InfraPoint[{v1,...,vk}] seeds a multi-source front.";
FindInfraShellCenter::usage = "FindInfraShellCenter[graph, shell] returns {center, radii} of a metric shell as a weighted InfraPoint and a sorted radius list; shell is a vertex list or an InfraShell. Method (\"MaximalChordsBisectors\" (default): bisect the shell's longest chords and union the midpoints, mass = bisection multiplicity, radius = union of integer arms; \"EquidistantPoints\": every vertex equidistant from the whole shell, unweighted, radius = common distance). \"MaximalChordsBisectors\" sub-options (inside the Method spec): \"Maximality\" (\"PerVertex\" (default) | \"Diameter\"), \"Distance\" (\"Extrinsic\" (default) | \"Intrinsic\", antipode-selection distance; \"Intrinsic\" is empty on a genuine sphere), \"Parity\" (All (default) | \"Even\" | \"Odd\").";
InfraShellQ::usage = "InfraShellQ[graph, vertexSet] tests whether vertexSet is a metric shell, i.e. some vertex c is equidistant from all of vertexSet at a common radius r and vertexSet equals the level set { v : d(c, v) == r }.";
SeparatesQ::usage = "SeparatesQ[graph, vertexSet, u, v] tests whether deleting vertexSet disconnects u from v.";

(* ===================== InfraBall ===================== *)

InfraBall::usage = "InfraBall[{ball}] is the unary form (one closed metric ball vertex set); InfraBall[{ball1, ..., ballk}] is the multi-realisation form. Scene-language constructor InfraBall[center, radius] is used inside InfraScene. The multi form is consumed by InfraSceneHighlight (induced-subgraph semantics).";
FindInfraBall::usage = "FindInfraBall[graph, c, r] returns InfraBall[{B_r(c)}] for the closed metric ball B_r(c) = { v : d(c, v) <= r }. A multi-anchor center (InfraPoint wrapper or a list of unary InfraPoint wrappers) spreads into one realisation per center.";
InfraBallQ::usage = "InfraBallQ[graph, vertexSet] tests whether vertexSet is a closed metric ball, i.e. equals { v : d(c, v) <= r } for some center c in vertexSet and some radius r.";
FindBallHull::usage = "FindBallHull[graph, S] returns the ball hull of S as an InfraSet: the intersection of all closed balls containing S, the smallest ball-convex (Mazur) superset. S is any Infra* object, a list of them, or a bare vertex list.";
BallHullQ::usage = "BallHullQ[graph, S] returns True if S is ball-convex, i.e. equals its own ball hull (an intersection of balls).";

(* ===================== InfraCircle ===================== *)

InfraCircle::usage = "InfraCircle[{cycle}] is the unary form; InfraCircle[{cycle1, ..., cyclek}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraCircle @ ... to collapse to multi via auto-flatten. Scene-language constructor InfraCircle[center, radius] is used inside InfraScene. The multi form is consumed by InfraSceneHighlight (sequential edges with auto-closure).";
FindInfraCircle::usage = "FindInfraCircle[graph, c, r] returns {InfraCircle[{cycle}]} for the canonical infra-circle around c at radius r (shortest separating cycle in the level surface), as an open vertex sequence. r is a scalar or {rmin, rmax} slab. FindInfraCircle[graph, c, r, n] returns a List of n unary InfraCircle[{cycle}] wrappers or $Failed; UpTo[n] returns up to n; All returns all. Option Properties (default {\"Separating\", \"Shortest\"}, order-insensitive set): \"Separating\" requires the cycle to disconnect c from {v: d(c,v) > rmax}; \"Shortest\" restricts to cycles tied at the minimum admissible length; empty {} permits any simple cycle in the level surface.";
FindInfraCycle::usage = "FindInfraCycle[graph, n] returns n shortest simple cycles in graph as unary InfraCircle[{cycle}] wrappers (open vertex sequences, sorted by length ascending); UpTo[n] returns up to n; All returns all. FindInfraCycle[graph, {k}, n] restricts to cycles of exactly length k; FindInfraCycle[graph, {kMin, kMax}, n] to cycles in the length range. Returns $Failed when fewer than n cycles exist. Results feed directly into NullHomotopicQ and FindInfraHomotopy.";
InfraCircleQ::usage = "InfraCircleQ[graph, cycle] tests whether the vertex sequence cycle is a metric circle (cyclic edge chain whose vertex set is a metric shell). Accepts both open and closed input.";

(* ===================== InfraPolygon ===================== *)

InfraPolygon::usage = "InfraPolygon[{poly}] is the unary form, where poly = {seg1, ..., segn} is a closed chain of unary InfraSegment sides; InfraPolygon[{poly1, ..., polyk}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraPolygon @ ... to collapse to multi via auto-flatten. Accessors [\"Sides\"] (the InfraSegment legs per realisation), [\"Length\"] (perimeter edge count per realisation), [\"Vertices\"] (corner vertices as unary InfraPoints).";
FindInfraPolygon::usage = "FindInfraPolygon[graph, {p1, ..., pn}] returns {InfraPolygon[{poly}]} for the polygon through corners p1, ..., pn (n >= 3), each side a geodesic between consecutive corners and the last side returning to p1. FindInfraPolygon[graph, verts, count] returns exactly count or $Failed; UpTo[count] returns up to count; All returns all polygons (the Cartesian product of per-side geodesic realisations). Default count = 1 (first geodesic per side). Corners accept bare vertices or unary InfraPoint. Options Properties / Method forward to the side geodesics (see FindInfraSegment).";
FindInfraRegularPolygon::usage = "FindInfraRegularPolygon[graph, As, n] returns {InfraPolygon[{poly}]} (a closed chain of geodesic sides) for a length-n cyclic vertex sequence whose k-diagonal distance d(v_i, v_{i+k}) satisfies As[[k]] for each k = 1, ..., Length[As] (Length[As] <= Floor[n/2]). Each entry of As is an Integer (exact value), {lo_Integer, hi_Integer} (constant across i, value in [lo, hi]), or Automatic (constant across i, any value); As[[1]] == Automatic enumerates simple n-cycles of graph and is slow on large graphs. FindInfraRegularPolygon[graph, As, n, count] / UpTo[count] / All controls multiplicity. Options: Properties ({} only at present; raises ::badproperty otherwise), Method (\"Exhaustive\" (default; FindCycle on the candidate-source graph, slot filters post-applied) | {\"Exhaustive\", \"Pruning\" -> spec}), \"From\" (All (default) | v (cycles containing v) | v -> r_Integer (cycles within NeighborhoodGraph[graph, v, r])).";
InfraPolygonQ::usage = "InfraPolygonQ[graph, poly] tests whether poly is a closed chain of geodesic InfraSegment sides (every leg a geodesic, consecutive legs sharing endpoints cyclically). Accepts an InfraPolygon wrapper or a bare leg list {seg1, ..., segn}.";
InfraRegularPolygonQ::usage = "InfraRegularPolygonQ[graph, cycle, As] tests whether the cycle is a regular n-gon w.r.t. the metric tuple As, with the same slot grammar as FindInfraRegularPolygon (Integer | {lo, hi} | Automatic per slot). Accepts open and closed input.";

(* ===================== InfraTriangle ===================== *)

InfraTriangle::usage = "InfraTriangle[{poly}] is the unary form, where poly = {seg1, seg2, seg3} is a closed chain of three unary InfraSegment sides; InfraTriangle[{poly1, ...}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraTriangle @ ... to collapse to multi via auto-flatten. Accessors [\"Sides\"], [\"Length\"], [\"Vertices\"] as for InfraPolygon.";
FindInfraTriangle::usage = "FindInfraTriangle[graph, {a, b, c}] returns {InfraTriangle[{poly}]} for the triangle through corners a, b, c (the n = 3 case of FindInfraPolygon); each side a geodesic. FindInfraTriangle[graph, verts, count] / UpTo[count] / All controls multiplicity over the Cartesian product of per-side geodesics; default count = 1. Options Properties / Method forward to the side geodesics (see FindInfraSegment).";
InfraTriangleQ::usage = "InfraTriangleQ[graph, poly] tests whether poly is a triangle (a closed chain of exactly three geodesic InfraSegment sides). Accepts an InfraTriangle wrapper or a bare three-leg list.";

(* ===================== InfraEllipticShell ===================== *)

InfraEllipticShell::usage = "InfraEllipticShell[{set}] is the unary form (one elliptic-shell vertex set); InfraEllipticShell[{set1, ..., setk}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraEllipticShell @ ... to collapse to multi via auto-flatten.";
FindInfraEllipticShell::usage = "FindInfraEllipticShell[graph, {p1, p2}, c] returns {InfraEllipticShell[{levelSet}]} for the elliptic shell { v : d(p1,v) + d(p2,v) == c }; c may be {cMin, cMax} for a tolerance band. FindInfraEllipticShell[graph, {p1, p2}, c, n] returns a List of n unary InfraEllipticShell[{set}] wrappers or $Failed; UpTo[n] returns up to n; All returns all. Options: Properties (list of \"Separating\" / \"Connected\"; empty default returns the level set itself), Method (\"Exhaustive\" (default; BFS over the peel-DAG, accepts nested {\"Exhaustive\", \"Pruning\" -> spec}) | \"Greedy\" (DFS, one realisation); ignored when Properties is empty).";
InfraEllipticShellQ::usage = "InfraEllipticShellQ[graph, vertexSet] tests whether vertexSet is an elliptic shell, i.e. equals { v : d(p1,v) + d(p2,v) == c } for some p1, p2, c.";

(* ===================== InfraQuadric ===================== *)

FindInfraQuadric::usage = "FindInfraQuadric[graph, {p1, ..., pk}, c] returns InfraObject[{ v : sum_i d(p_i, v) <= c }], the solid ellipsoid interior with foci p_i. FindInfraQuadric[graph, foci, {cMin, cMax}] returns the band { v : cMin <= sum_i d(p_i, v) <= cMax }. FindInfraQuadric[graph, foci, c, weights] uses the weighted signed-distance sum sum_i w_i d(p_i, v); weights {1, -1} give a hyperboloid (one branch via scalar c, two-sided via symmetric band {-c, c}). Foci accept bare vertices or InfraPoint wrappers (multi-realisation reduced to first).";

(* ===================== InfraEllipse ===================== *)

InfraEllipse::usage = "InfraEllipse[{cycle}] is the unary form; InfraEllipse[{cycle1, ..., cyclek}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraEllipse @ ... to collapse to multi via auto-flatten.";
FindInfraEllipse::usage = "FindInfraEllipse[graph, {p1, p2}, c] returns {InfraEllipse[{cycle}]} for the shortest separating cycle in the level-surface subgraph { v : cMin <= d(p1,v) + d(p2,v) <= cMax }, as an open vertex sequence (c may be scalar or {cMin, cMax}; sparse level sets usually require a range). FindInfraEllipse[graph, {p1, p2}, c, n] returns a List of n unary InfraEllipse[{cycle}] wrappers or $Failed (cycles sorted by length ascending); UpTo[n] returns up to n; All returns all. Options: Properties (default {\"Separating\"}; cycle disconnects {sum < cMin} from {sum > cMax}; {} permits any cycle in the level surface), Method (\"Peel\" (default; BFS peel-DAG on the level-set vertices, robust on sparse level sets) | \"Exhaustive\" (FindCycle + filter + length sort, accepts nested {\"Exhaustive\", \"Pruning\" -> spec}) | \"Greedy\" (first admissible cycle by length, one realisation)).";
InfraEllipseQ::usage = "InfraEllipseQ[graph, cycle] tests whether the vertex sequence cycle is a metric ellipse (cyclic edge chain whose vertex set is an elliptic shell). Accepts both open and closed input.";

(* ===================== InfraPlane ===================== *)

InfraPlane::usage = "InfraPlane[{set}] is the unary form (one bisecting hyperplane); InfraPlane[{set1, ..., setk}] is the multi-realisation form. Find* returns a List of unary wrappers; wrap with InfraPlane @ ... to collapse to multi via auto-flatten. Scene-language constructors InfraPlane[p1, p2] and InfraPlane[p1, p2, {lo, hi}] are used inside InfraScene.";
FindInfraBisectingHyperplane::usage = "FindInfraBisectingHyperplane[graph, p1, p2] returns {InfraPlane[{slab}]} for the bisector { v : d(p1, v) == d(p2, v) } (default Properties -> {}). FindInfraBisectingHyperplane[graph, p1, p2, n] returns a List of n unary InfraPlane[{set}] wrappers or $Failed; UpTo[n] returns up to n; All returns all. A positional {lo, hi} widens the bisector slab to lo <= d(p1, v) - d(p2, v) <= hi. Options: Properties (list of \"Separating\" / \"Connected\"; AND-conjoined filter on candidate subsets), Method (\"Exhaustive\" (default; BFS over the peel-DAG, accepts nested {\"Exhaustive\", \"Pruning\" -> spec}) | \"Greedy\" (DFS, one realisation)).";

(* ===================== InfraRay ===================== *)

InfraRay::usage = "InfraRay[{ray}] is the unary form (one pointed half-line from a base vertex O); InfraRay[{ray1, ..., rayk}] is the multi-realisation form. Each ray is a vertex sequence {O, ..., w} with w an inextensible endpoint. Find* returns a List of unary wrappers; wrap with InfraRay @ ... to collapse to multi via auto-flatten. Consumed by InfraSceneHighlight (sequential-edge semantics).";
FindInfraRay::usage = "FindInfraRay[graph, O, v] returns {InfraRay[{ray}]} for one pointed half-line from O in v's direction: the half of a maximal geodesic line through O and v starting at O and ending at the far inextensible endpoint. FindInfraRay[graph, O, v, n] returns a List of n unary InfraRay[{ray}] wrappers or $Failed; UpTo[n] / All controls multiplicity. O and v accept InfraPoint[{...}] for multi-anchor spread.";

(* ===================== InfraPolyline ===================== *)

InfraPolyline::usage = "InfraPolyline[{poly}] is the unary form: poly = {seg1, ..., segk} is a list of unary InfraSegment[{path_i}] with consecutive legs sharing their endpoint (Last[path_i] == First[path_{i+1}]). InfraPolyline[{poly1, ..., polym}] is the multi-realisation form. Consumed by InfraSceneHighlight (each realisation flattens to one concatenated vertex sequence; sequential-edge semantics).";
FindInfraPolylineSubdivision::usage = "FindInfraPolylineSubdivision[graph, path] returns {InfraPolyline[{{seg1, ..., segk}}]} where the legs are the fewest geodesic InfraSegments whose knots are path-vertices and each leg is a shortest path since the previous knot. Option: \"MaxLength\" (Infinity (default) | numeric L) caps every leg's graph-length at L.";
InfraPolylineQ::usage = "InfraPolylineQ[graph, poly] tests whether poly = {seg1, ..., segk} of unary InfraSegment wrappers is a valid polyline in graph: every leg is a geodesic and consecutive legs share an endpoint. Accepts the wrapped form InfraPolyline[{...}] as well (AllTrue over realisations).";

(* ===================== InfraRevolution ===================== *)

InfraObject::usage = "InfraObject[vs] wraps a vertex set vs as a single graph-geometric object; consumed by InfraSceneHighlight (induced-subgraph semantics).";
InfraRevolution::usage = "InfraRevolution[axis, profile] is the scene-language constructor for a rotational object inside InfraScene.";
FindInfraRevolution::usage = "FindInfraRevolution[graph, axis, profile] returns InfraObject[set] for the rotational vertex set around axis with the given radius profile. The axis is internally extended by +1 position on each side via ExtendInfraSegment[..., \"Length\" -> 1] so the orthogonality test sees a one-step extension at each endpoint. The profile may be NumericQ (constant), a List of length |axis|, an Association vertex -> radius, or any callable applied to index 1..|axis|. Options: \"Form\" (\"Solid\" (default) | \"Surface\"); Method (\"Voronoi\" (default) -- closest extended position must be in the original axis range; \"PerpendicularBisector\" -- u included at position i iff d(u, v_{i-1}) == d(u, v_{i+1}); \"Balls\" -- union of metric balls B_{r_i}(c_i), the varying-radius tubular neighborhood, which also works for cyclic / non-extendable axes).";
FindInfraCylinder::usage = "FindInfraCylinder[graph, axis, r] returns InfraObject[set] for the constant-radius rotational set around axis. Defaults to Method -> \"Balls\" (the r-neighborhood of the axis, i.e. all v with d(v, c) <= r for some axis vertex c); pass Method -> \"Voronoi\" for the flat-capped variant. Inherits remaining FindInfraRevolution options.";
FindInfraCone::usage = "FindInfraCone[graph, axis, slope] returns InfraObject[set] for the cone of given slope with apex at axis[[1]]: radii are slope * Range[0, Length[axis] - 1]. Option \"Apex\" (First (default) | Last) flips the apex end; inherits remaining options from FindInfraRevolution.";
InfraRevolutionQ::usage = "InfraRevolutionQ[graph, vs, axis, profile] tests whether vs equals the rotational vertex set around axis with the given radius profile. Option \"Form\" matches FindInfraRevolution.";

(* ===================== EuclideanSpace ===================== *)

InfraScalarProduct::usage = "InfraScalarProduct[graph, o, u, v] returns the base-point-relative scalar product of u and v with respect to o. Option: Method (\"Alexandrov\" (default) -- d(o,u) d(o,v) cos(theta_0) which collapses to (d(o,u)^2 + d(o,v)^2 - d(u,v)^2)/2; {\"Alexandrov\", \"Curvature\" -> k} -- same with spherical / hyperbolic law of cosines in M_k^2; \"Parallelogram\" -- polarization identity (||u+v||^2 - ||u-v||^2)/4 via FindInfraLinearCombination).";
FindInfraLinearCombination::usage = "FindInfraLinearCombination[graph, o, {{lambda1, u1}, {lambda2, u2}, ...}] returns a List of unary InfraPoint[{v}] wrappers for the multi-valued vertex realisation of sum_i lambda_i u_i with base point o, computed as scaled-then-pairwise-summed left-to-right. With n / UpTo[n] / All controls multiplicity. Options: \"ScaleMethod\" (Automatic (default), \"Metric\", \"Line\", \"Midpoint\"); \"SumMethod\" (\"Metric\" (default), \"Parallel\").";
InfraAngle::usage = "InfraAngle[graph, {q1, p, q2}] returns an angle at p in radians. Option: Method (\"Arclength\" (default) -- delete the open ball of radius Min[d(p, q1), d(p, q2)] around p and return the shortest q1-q2 path length outside, divided by the radius (synthetic radian measure); \"Alexandrov\" -- the comparison-triangle angle at p in the Euclidean k = 0 model via the law of cosines; {\"Alexandrov\", \"Curvature\" -> k} -- the same angle in M_k^2 (spherical / Euclidean / hyperbolic) for arbitrary k). For the raw un-arccos'd scalar product use InfraScalarProduct[graph, p, q1, q2].";

(* ===================== InfraCurveGeometry ===================== *)

TurningAngles::usage = "TurningAngles[graph, path] returns the list of discrete exterior angles Pi - InfraAngle[graph, {v_{i-1}, v_i, v_{i+1}}] at each interior vertex of the polygonal curve path = {v_1, ..., v_k}; closed cycles (First[path] == Last[path]) include the wrap-around triple. TurningAngles[graph, polyline] returns the list of turning angles at the knot vertices of an InfraPolyline (one list per realisation); geodesic-interior vertices contribute no turning by construction.";
TotalCurvature::usage = "TotalCurvature[graph, path] returns the discrete total curvature Total @ TurningAngles[graph, path] of the polygonal curve.";
TotalAbsoluteCurvature::usage = "TotalAbsoluteCurvature[graph, path] returns Total @ Abs @ TurningAngles[graph, path], the discrete analogue of the Fenchel-side integral of |kappa|.";
TurningNumber::usage = "TurningNumber[graph, cycle] returns TotalCurvature[graph, cycle] / (2 Pi); integer in the smooth planar case, a real-valued empirical quantity on graphs.";

(* ===================== AlexandrovGeometry ===================== *)

ComparisonTriangle::usage = "ComparisonTriangle[a, b, c] returns the Wolfram Triangle in R^2 with side lengths {a, b, c} (a opposite p, b opposite q, c opposite r). ComparisonTriangle[a, b, c, \"Curvature\" -> k] for k != 0 returns InfraComparisonTriangle[<|\"Sides\" -> ..., \"Curvature\" -> k, \"Angles\" -> {alpha_p, alpha_q, alpha_r}|>] in M_k^2. ComparisonTriangle[graph, p, q, r, \"Curvature\" -> k] reads the side lengths from the graph.";
InfraComparisonTriangle::usage = "InfraComparisonTriangle[<|...|>] is the wrapper head for non-Euclidean comparison triangles returned by ComparisonTriangle. Accessors: [\"Sides\"], [\"Curvature\"], [\"Angles\"].";
CATInequalityQ::usage = "CATInequalityQ[graph, {p, q, r}, k : 0] tests whether the geodesic triangle on {p, q, r} satisfies the CAT(k) thinness inequality. Option Method (\"ApexSide\" (default) -- d(apex, x) <= d_k_bar(apex', x') for every interior vertex x on the side opposite to each apex; \"TwoRays\" -- d(x, y) <= d_k_bar(x', y') for every cross-ray pair (x, y) on the two rays emanating from each apex). Returns Indeterminate when k > 0 and the triangle perimeter exceeds 2 Pi / Sqrt[k].";
InfraCurvature::usage = "InfraCurvature[graph, v] returns the local Alexandrov upper-curvature bound at v: L^2 times the supremum of per-triangle CAT bounds over all triangles whose three vertices sit inside B_L(v), with L = GraphDiameter[graph] by default. Option: \"Radius\" (Automatic | Integer L) selects the ball radius; reported curvature is rescaled by L^2 to match the (edge / L)^-2 unit convention. InfraCurvature[graph] returns an Association[v -> kappa_v] over all vertices.";

(* ===================== PathSpace ===================== *)

SelectInfraPath::usage = "SelectInfraPath[graph, paths] returns one path drawn from the bundle treated as a finite metric space in path-space. SelectInfraPath[graph, paths, n] returns exactly n or $Failed; UpTo[n] returns up to n; All returns the whole pool. Options mirror FindInfraPoint: \"From\" (All (default), \"Center\", \"Periphery\", \"MostVisited\", anchor -> spec, InfraSegment[{...}] -> spec, {\"Min\", scoreFn} / {\"Max\", scoreFn} with user-supplied path-aggregated scoreFn[path] returning a comparable value), \"Distance\" (None (default), \"Max\", d, {dMin, dMax}), \"Metric\" (\"Hausdorff\" (default), \"Frechet\", \"MeanFrechet\"), \"MaxCliques\". Accepts InfraSegment and InfraRay wrappers; preserves the wrapper. Operator form SelectInfraPath[graph, n, opts][paths].";
SelectInfraCycle::usage = "SelectInfraCycle[graph, cycles] returns one cycle drawn from the bundle in path-space. SelectInfraCycle[graph, cycles, n] returns exactly n or $Failed; UpTo[n] returns up to n; All returns the whole pool. Options mirror SelectInfraPath, with two extra \"From\" values: \"ShortestCircumference\", \"LongestCircumference\". Path-space metric distances factor cyclic rotation so they are rotation-invariant. Accepts InfraCircle[cycles_List]; preserves the wrapper. Operator form SelectInfraCycle[graph, n, opts][cycles].";
EmbeddingClosest::usage = "EmbeddingClosest[graph, bundle, {p1, p2}] keeps the bundle elements whose drawing under GraphEmbedding is Hausdorff-closest to the straight Euclidean segment p1-p2. EmbeddingClosest[graph, bundle, {center, radius}] keeps the bundle elements Hausdorff-closest to the Euclidean circle of given centre and radius. EmbeddingClosest[graph, bundle, curve] keeps the bundle elements Hausdorff-closest to an arbitrary embedded curve, where curve is a Line / BSplineCurve / BezierCurve or a list of at least three plane points in the embedding's coordinates. Dispatch is by reference shape: {vertex, vertex} for paths, {vertex, numeric} for cycles, a curve or >=3-point list for the best-approximating path. Accepts bare lists, InfraSegment / InfraLine / InfraPath / InfraRay / InfraCircle wrappers, or homogeneous lists of unary wrappers; wrappers are preserved. Operator form EmbeddingClosest[graph, ref][bundle].";

FindEmbeddingClosestPath::usage = "FindEmbeddingClosestPath[graph, curve] snaps an arbitrary embedded curve to a graph walk and returns InfraPath[{walk}] tracing it: each sampled curve point is mapped to its nearest vertex under the graph embedding, consecutive repeats are dropped, and successive anchors are joined by geodesics. curve is a Line / BSplineCurve / BezierCurve or a list of plane points in the embedding's coordinates. Unlike EmbeddingClosest (which selects from a supplied bundle), this constructs the path, so it works for shapes with no enumerable bundle (spirals, figure-eights).";
GeodesicSprayGraph::usage = "GeodesicSprayGraph[graph, c] returns the BFS DAG rooted at c: a directed graph with edge u -> v whenever d(c, v) = d(c, u) + 1 and u-v is an edge of graph. Sinks are peripheral vertices reachable from c; directed paths c -> sink are exactly the maximal geodesics from c. GeodesicSprayGraph[graph, InfraPoint[{c1, ..., ck}]] uses multi-source BFS. GeodesicSprayGraph[graph, pairs] returns the union of geodesics between the listed vertex pairs. Options: \"AxisLength\" (truncate the source-spray DAG at depth k; default All), \"PathThickness\" (per-pair Hausdorff threshold; 0 keeps one geodesic per pair, Infinity keeps all), \"Directed\".";
PathSubgraph::usage = "PathSubgraph[graph, u, v] returns the union of all shortest u-v paths. PathSubgraph[graph, u, v, k] (or UpTo[k]) caps path length; PathSubgraph[graph, u, v, All] returns the full simple-path subgraph. Option: \"Directed\".";

(* ===================== Homotopy ===================== *)

InfraHomotopy::usage = "InfraHomotopy[{chain}] is the unary form: one homotopy chain {p0, p1, ..., pk} of intermediate walks produced by k elementary moves from p0 to pk. InfraHomotopy[{chain1, ..., chaink}] is the multi-realisation form. Find* finders return a List of unary InfraHomotopy[{chain}] wrappers; wrap that list with InfraHomotopy @ ... to collapse to multi via auto-flatten.";
FindInfraHomotopyRepresentative::usage = "FindInfraHomotopyRepresentative[graph, obj] returns {head[{w}]} for one length-shortest walk w in obj's homotopy class, where head matches the input wrapper (InfraPath / InfraLoop / InfraString; InfraCircle coerces to InfraString). FindInfraHomotopyRepresentative[graph, obj, n] / UpTo[n] / All controls multiplicity. Options: Method (\"Exhaustive\" (default; BFS), {\"Exhaustive\", \"Pruning\" -> spec}, \"Greedy\" (DFS contracting moves only)), \"FreeHomotopy\" (False (default); True allows endpoint slides on InfraPath and base-point rotation on InfraLoop), \"NullHomotopicCycles\" (default {1, 2, 3}), \"MaxLength\" (Automatic), \"MaxMoves\" (Infinity).";
FindInfraHomotopyRepresentativeHomotopy::usage = "FindInfraHomotopyRepresentativeHomotopy[graph, obj] returns {InfraHomotopy[{chain}]} for one reduction chain {obj, ..., m} of elementary moves ending at a representative m. FindInfraHomotopyRepresentativeHomotopy[graph, obj, n] / UpTo[n] / All controls multiplicity. Same options as FindInfraHomotopyRepresentative.";
FindInfraHomotopy::usage = "FindInfraHomotopy[graph, a, b] returns {InfraHomotopy[{chain}]} exhibiting a chain of elementary moves from a to b. Endpoints a and b must share a wrapper head (InfraPath / InfraLoop / InfraString; InfraCircle coerces to InfraString). FindInfraHomotopy[graph, a, b, n] / UpTo[n] / All controls multiplicity. Options: Method (\"Exhaustive\" (default; walk-space BFS), {\"Exhaustive\", \"Pruning\" -> spec}, \"Greedy\" (DFS picking the move minimising symmetric Hausdorff distance to target)), \"FreeHomotopy\" (False (default); True allows endpoint slides on InfraPath and base-point rotation on InfraLoop), \"NullHomotopicCycles\" (default {1, 2, 3}), \"MaxLength\" (Automatic), \"MaxMoves\" (Infinity).";
HomotopicQ::usage = "HomotopicQ[graph, a, b] tests whether a and b are in the same homotopy class. a and b must share a wrapper head (InfraPath / InfraLoop / InfraString; InfraCircle coerces to InfraString). Spreads over multi-realisation inputs as a Cartesian-AllTrue conjunction. Inherits FindInfraHomotopy options.";
NullHomotopicQ::usage = "NullHomotopicQ[graph, cycle] tests whether a closed walk is null-homotopic. Accepts a bare closed walk (auto-closed via {cycle, First[cycle]}), an InfraLoop[{...}], InfraString[{...}], or InfraCircle[{...}] (Cartesian-AllTrue over realisations). Inherits FindInfraHomotopy options.";
HomotopyMoveType::usage = "HomotopyMoveType[walk1, walk2] classifies the elementary move walk1 -> walk2 as \"Contract\" (walk shortens), \"Extend\" (walk lengthens), or \"Lateral\" (walks have the same length; only possible for moves that swap arcs of equal length on an even-length null-homotopic cycle).";
HomotopyMoveTypes::usage = "HomotopyMoveTypes[chain] applies HomotopyMoveType to each consecutive pair in chain. HomotopyMoveTypes[InfraHomotopy[{chain}]] returns the labels for the unary wrapper; HomotopyMoveTypes[InfraHomotopy[reps]] returns one label list per realisation.";

(* ===================== MetricAlgebra ===================== *)

MetricInterval::usage = "MetricInterval[graph, u, v] returns the vertex set { w : d(u, w) + d(w, v) == d(u, v) } -- the union of all geodesics from u to v.";
GeodesicMultiplicity::usage = "GeodesicMultiplicity[graph, u, v] returns the number of distinct geodesics from u to v, computed as (A^d)[u, v] where d = GraphDistance[graph, u, v].";
GeodesicMultiplicityMatrix::usage = "GeodesicMultiplicityMatrix[graph] returns {D, M} where D is the distance matrix and M[i, j] is the number of geodesics from vertex i to vertex j.";
MedianVertices::usage = "MedianVertices[graph, vs] returns the vertices minimising the sum of distances to vs. A graph is a median graph iff every triple has a unique median.";
FindSegmentHull::usage = "FindSegmentHull[graph, S] returns the smallest superset of S closed under MetricInterval (the segment operator), as an InfraSet. S is any Infra* object, a list of them, or a bare vertex list. Option \"LineStructure\" (None (default), or an InfraLineStructure / list of lines) closes under the chosen-geodesic stretch on that fixed family instead of all geodesics.";
SegmentHullQ::usage = "SegmentHullQ[graph, S] returns True if S is closed under the segment operator, i.e. equals its own FindSegmentHull. Option \"LineStructure\" as in FindSegmentHull.";

(* ===================== Visit measure ===================== *)

InfraMeasure::usage = "InfraMeasure[obj] returns the vertex occupation measure <|v -> appearances|> of an Infra* wrapper -- the marginal of its realization bundle onto its vertices. InfraMeasure[graph, obj] is graph-aware and unlocks the edge measure. Options \"On\" (\"Vertices\" (default), \"Edges\", \"Both\") and Method (\"Occupation\" (default) divides by numReps, the membership measure in [0,1]; \"Probability\" divides by total appearances, the distribution summing to 1).";

(* ===================== InfraSet ===================== *)

InfraSet::usage = "InfraSet[vs] wraps a vertex list vs as a set; coerces any Infra* wrapper to its underlying vertex set. Accessors: [\"Vertices\"] (the vertex list), [\"Length\"] (cardinality).";

FindInfraEquidistantSet::usage = "FindInfraEquidistantSet[graph, {p1, ..., pn}] returns the equidistant set {v : d(p1, v) == ... == d(pn, v)} as an InfraSet, the intersection of the n-1 consecutive perpendicular bisectors. FindInfraEquidistantSet[graph, {p1, ..., pn}, {lo, hi}] thickens each consecutive bisector to the slab lo <= d(p_i, v) - d(p_{i+1}, v) <= hi.";

InfraBoundary::usage = "InfraBoundary[g, s] is the boundary of the vertex set s (a bare vertex list or any Infra* object) in g, returned as an InfraSet. Option Method (\"Combinatorial\" (default), the inner vertex boundary via GraphBoundary; {\"Alexandrov\", \"Radius\" -> r}, the two-sided cl(s)\\int(s) in the closed-r-ball topology, default r = 1).";

InfraInterior::usage = "InfraInterior[g, s] is the interior of the vertex set s (a bare vertex list or any Infra* object) in g, returned as an InfraSet. Option Method (\"Combinatorial\" (default), s minus its inner boundary via GraphInterior; {\"Alexandrov\", \"Radius\" -> r}, the topological interior in the closed-r-ball topology, default r = 1).";

(* ===================== Coordinatization ===================== *)

(* RadarCoordinates / ResistanceCoordinates usage now lives in the Infrageometry paclet. *)

FindInfraRadarBasis::usage = "FindInfraRadarBasis is deprecated; use FindResolvingSet (Infrageometry paclet). FindInfraRadarBasis[graph, n, m] returns up to n resolving sets by ascending size.";
InfraRadarBasisQ::usage = "InfraRadarBasisQ is deprecated; use ResolvingSetQ (Infrageometry paclet). InfraRadarBasisQ[graph, basis] tests whether basis is a resolving set.";
OrthogonalCoordinates::usage = "OrthogonalCoordinates[graph, c, {a1, a2, ...}, v] returns the Z-valued displacement of v on each axis ai through the centre c; OrthogonalCoordinates[graph, c, {a1, a2, ...}] returns the Association for all vertices. Centre c is a vertex or InfraPoint; each axis ai is an InfraSegment, InfraLine, or vertex sequence. Option \"SelectCoordinate\" (projection-tie reducer applied to the shifted tied list ix_v - k: \"Centered\" (default; 0 if 0 in shifted, else Round[Median]), Min, Max, Mean, Median, All, or any user function).";
FindInfraOrthogonalFrame::usage = "FindInfraOrthogonalFrame[graph, c, axisLength] returns one orthogonal frame at centre c with each axis half-depth constrained by axisLength (All | n_Integer | UpTo[n] | {min, max}): a list of InfraSegment axes (full metric lines through c, c strictly interior), mutually perpendicular at c. FindInfraOrthogonalFrame[graph, c, axisLength, n] returns exactly n distinct frames or $Failed; UpTo[n] returns up to n; All returns every frame. Centre is a vertex or InfraPoint[{c1, ..., ck}]. Options: Method (Automatic = \"Exhaustive\", or \"Greedy\"), \"AxisCount\" (Automatic | k | UpTo[k] | All), \"BranchSampleSize\" (Exhaustive subsample cap), \"SelectCoordinate\" (projection-tie reducer; perpendicularity at c is defined as the per-axis coord being 0 under this reducer applied to the shifted tied list ix_w - k; \"Centered\" (default; 0 if 0 in shifted, else Round[Median]), Min, Max, Mean, Median, All, ...). For the no-centre form use FindInfraSpanningAxes.";
FindInfraSpanningAxes::usage = "FindInfraSpanningAxes[graph, n] returns n mutually well-separated longest geodesics across graph (greedy, no fixed center) or $Failed; UpTo[n] returns up to n; All returns every axis above the separation threshold. Options: \"AxisDistance\" (\"MinEndpoint\" | \"Hausdorff\" | \"Separation\"), \"MinLength\", \"MinSeparation\", \"AxisThickness\", \"RandomPick\". For axes through a fixed center vertex use FindInfraOrthogonalFrame.";

(* ===================== TarskiGeometry ===================== *)

BetweennessQ::usage = "BetweennessQ[graph, u, w, v] tests Tarski's betweenness B(u, w, v): w lies on a geodesic from u to v.";
EquidistanceQ::usage = "EquidistanceQ[graph, a, b, c, d] tests Tarski's equidistance ab == cd: d(a, b) == d(c, d).";
TarskiStructure::usage = "TarskiStructure[graph] returns a memoized Association bundling the Tarski primitives: \"Vertices\", \"VertexIndex\", \"Distances\", \"Betweenness\", \"Equidistance\", \"Diameter\".";
TarskiBetweennessTensor::usage = "TarskiBetweennessTensor[graph] returns the sparse rank-3 tensor whose nonzero positions are the (i, j, k) with B(v_i, v_j, v_k).";
TarskiEquidistanceClasses::usage = "TarskiEquidistanceClasses[graph] returns the partition of unordered vertex pairs by distance value.";
TarskiCongruenceReflexivityQ::usage = "TarskiCongruenceReflexivityQ[graph] tests Tarski axiom A1 (ab == ba). Always True on undirected simple graphs.";
TarskiCongruenceTransitivityQ::usage = "TarskiCongruenceTransitivityQ[graph] tests Tarski axiom A2 (transitivity of ==). A tautology of equality.";
TarskiCongruenceIdentityQ::usage = "TarskiCongruenceIdentityQ[graph] tests Tarski axiom A3 (ab == cc implies a == b). Holds on connected simple graphs.";
TarskiSegmentConstructionQ::usage = "TarskiSegmentConstructionQ[graph] tests Tarski axiom A4 (segment construction). Generally False on finite graphs.";
TarskiFiveSegmentsQ::usage = "TarskiFiveSegmentsQ[graph] tests Tarski axiom A5 (five segments). Holds on median graphs. Brute O(n^8); option \"MaxTuples\" caps the search (Indeterminate if the cap is hit).";
TarskiBetweennessIdentityQ::usage = "TarskiBetweennessIdentityQ[graph] tests Tarski axiom A6 (B(a, b, a) implies a == b). Always True on connected simple graphs.";
TarskiInnerPaschQ::usage = "TarskiInnerPaschQ[graph] tests Tarski axiom A7 (Inner Pasch). Holds on median graphs; fails on cycles >= 5 and on Petersen.";
TarskiLowerDimensionQ::usage = "TarskiLowerDimensionQ[graph] tests Tarski axiom A8 (three non-collinear points exist).";
TarskiUpperDimensionQ::usage = "TarskiUpperDimensionQ[graph] tests Tarski axiom A9 (three points equidistant from two distinct points are collinear). False on graphs of effective dimension >= 3.";
TarskiEuclidAxiomQ::usage = "TarskiEuclidAxiomQ[graph] tests Tarski axiom A10 (Euclid's parallel-axiom variant). Stub: returns Indeterminate.";
TarskiContinuityQ::usage = "TarskiContinuityQ[graph] tests Tarski axiom A11 (Dedekind continuity). Always False on finite graphs.";
TarskiAxiomQ::usage = "TarskiAxiomQ[graph] returns an Association with the per-axiom result for all eleven Tarski*Q predicates.";
FindTarskiCounterexample::usage = "FindTarskiCounterexample[graph, predQ] returns one vertex tuple witnessing the failure of the Tarski axiom predicate predQ, or $Failed. With n / UpTo[n] / All caps witness count. Returns $Failed for always-True axioms and TarskiContinuityQ.";

(* ===================== ProjectiveGeometry ===================== *)

SameDirectionQ::usage = "SameDirectionQ[graph, O, v, w] tests whether v and w lie in the same direction at O (some maximal geodesic through O contains both).";
CollinearQ::usage = "CollinearQ[graph, vertices] tests whether all listed vertices lie on a common line.";
ConcurrentQ::usage = "ConcurrentQ[graph, lines] tests whether all listed lines share a common vertex.";
UniquePencilQ::usage = "UniquePencilQ[graph, O] tests whether every direction at O is single-valued.";
UniqueCollinearQ::usage = "UniqueCollinearQ[graph, vertices] tests whether the listed vertices lie on a unique common line.";
UniqueConcurrentQ::usage = "UniqueConcurrentQ[graph, lines] tests whether the listed lines share exactly one common vertex.";
WhiteheadW1Q::usage = "WhiteheadW1Q[graph] tests Whitehead axiom W1: every line has at least three vertices.";
WhiteheadW2Q::usage = "WhiteheadW2Q[graph] tests Whitehead axiom W2: through any two distinct vertices there is exactly one line (geodetic property).";
WhiteheadW3Q::usage = "WhiteheadW3Q[graph] tests Whitehead axiom W3 (intersection property). O(|V|^4); use on small graphs.";
ProjectivePlaneGraphQ::usage = "ProjectivePlaneGraphQ[graph] tests whether graph is a synthetic projective plane: W1 && W2 && W3 with non-degeneracy.";

(* ===================== Enumeration ===================== *)

EnumerateGraphs::usage = "EnumerateGraphs[n, predQ] returns all connected n-vertex graphs from GraphData satisfying predQ. EnumerateGraphs[n, predQ, k] returns exactly k or $Failed; UpTo[k] returns up to k; All returns all. Option: \"From\" (override the default GraphData generator with a list).";

(* ===================== Example graphs ===================== *)















(* ===================== Scenes ===================== *)

InfraScene::usage = "InfraScene[objects, hypotheses] constructs a scene descriptor from symbolic objects and construction/assertion hypotheses. Properties: scene[\"Steps\"], [\"Constructions\"], [\"Assertions\"], [\"DependencyGraph\"].";
FindInfraScene::usage = "FindInfraScene[scene, graph] evaluates all construction steps and returns InfraInstance objects; the third argument can be n (cap step count) or an Association of pre-fixed bindings. Option: \"PruneProbability\".";
InfraInstance::usage = "InfraInstance[bindings] wraps a solved binding association from FindInfraScene. Read out via InfraInstance[bindings, sym] or InfraInstance[bindings, {sym1, sym2, ...}].";
InfraGeometricStep::usage = "InfraGeometricStep[{hyp1, hyp2, ...}] groups hypotheses into a manual construction step. InfraGeometricStep[{hyps...}, label] adds a label.";
InfraLine::usage = "InfraLine[p, q] represents maximal geodesic extensions through p and q. InfraLine[path] extends a given path. Multi-realisations are returned as InfraSegment[{...}] (the only path-shaped wrapper).";
InfraIntersection::usage = "InfraIntersection[obj1, obj2, ...] returns the vertex-set intersection of the given Infra* objects as an InfraSet (each object's contribution is the union of vertices across its realisations). Also used symbolically in InfraScene hypotheses, where it stays inert until bindings resolve.";
InfraUnion::usage = "InfraUnion[obj1, obj2, ...] returns the vertex-set union of the given Infra* objects as an InfraSet (each object's contribution is the union of vertices across its realisations).";
InfraDistance::usage = "InfraDistance[g, p, q] is the graph distance between p and q in g, where each is a bare vertex or any Infra* wrapper (InfraPoint, InfraSegment, InfraPath, InfraLoop, InfraString, InfraLine, InfraRay, InfraCircle, InfraEllipse, InfraPolyline, InfraShell, InfraEllipticShell, InfraPlane, InfraBall, InfraObject, InfraSet); the result is aggregated over the cross-product of underlying vertex sets via the \"Aggregation\" option (Min default, also Max / Mean / any List -> Number). InfraDistance[p, q] without a graph is also recognised inside InfraScene assertions.";
InfraSegmentQ::usage = "InfraSegmentQ[s] asserts that s is a valid geodesic segment.";
InfraPathQ::usage = "InfraPathQ[w] asserts that w is a valid simple path (consecutive adjacency, no repeated vertices).";
InfraShellQ::usage = "InfraShellQ[vs] asserts that vs is a valid metric shell.";
InfraPlaneQ::usage = "InfraPlaneQ[h, p1, p2] asserts that h is a valid bisecting hyperplane between p1 and p2.";
InfraCircleQ::usage = "InfraCircleQ[c] asserts that c is a valid metric circle.";
InfraLineQ::usage = "InfraLineQ[s] asserts that s is a maximal geodesic.";
InfraParallelQ::usage = "InfraParallelQ[l1, l2] asserts that two lines are parallel.";
InfraPerpendicularQ::usage = "InfraPerpendicularQ[l1, l2] asserts that two lines are perpendicular at every common vertex.";
InfraIntersectQ::usage = "InfraIntersectQ[s1, s2] asserts that two sets intersect.";
InfraRevolutionQ::usage = "InfraRevolutionQ[vs, axis, profile] asserts that vs is the rotational vertex set around axis with the given radius profile.";

(* ===================== Highlights / Viewers ===================== *)

$InfraPointColor::usage   = "Default highlight color for InfraPoint objects.";
$InfraSegmentColor::usage = "Default highlight color for InfraSegment objects.";
$InfraShellColor::usage   = "Default highlight color for InfraShell objects.";
$InfraBallColor::usage    = "Default highlight color for InfraBall objects.";
$InfraPlaneColor::usage   = "Default highlight color for InfraPlane objects.";
$InfraCircleColor::usage  = "Default highlight color for InfraCircle objects.";
$InfraRayColor::usage     = "Default highlight color for InfraRay objects.";
$InfraObjectColor::usage  = "Default highlight color for InfraObject objects.";

InfraSceneHighlight::usage = "InfraSceneHighlight[g, multiObjects] renders a list of multi-objects diffusely on graph g, with intensity scaling by overlap within each object and color-blending across objects. InfraSceneHighlight[g, obj] is the single-object shortcut for InfraSceneHighlight[g, {obj}]. Each entry is auto-classified by representation; explicit Infra* wrappers force the intended semantics. Per-object style overrides via `entry -> color`, `entry -> Directive[dirs]`, `Style[entry, dirs__]`, or `entry -> {opts...}` with a flat option list auto-sorted into vertex (VertexStyle / VertexSize / VertexShapeFunction), edge (EdgeStyle / EdgeShapeFunction), and per-object diffusion (\"OpacityRange\" / \"ThicknessRange\" / \"PointSizeRange\") channels. Options: \"OpacityRange\", \"ThicknessRange\", \"PointSizeRange\".";
InfraSceneViewer::usage = "InfraSceneViewer[scene, graph] is an interactive visualisation of an InfraScene on a graph; an optional third Association of pre-fixed bindings is supported. Controls: step arrows, \"Branch\"/\"Diffuse\" mode setter, and (in Branch mode) branch arrows.";
PointViewer::usage = "PointViewer[g] is an interactive viewer for selecting points in graph g. PointViewer[g, sym] stores the current selection in sym.";
SegmentViewer::usage = "SegmentViewer[g] is an interactive viewer for exploring geodesic segments in graph g.";
ShellViewer::usage = "ShellViewer[g] is an interactive viewer for exploring metric shells in graph g. Method setter: \"Metric\" | \"Separating\".";
CircleViewer::usage = "CircleViewer[g] is an interactive viewer for exploring separating cycles in graph g.";

(* ===================== InfraEquality ===================== *)

InfraEqualQ::usage = "InfraEqualQ[graph, a, b] tests equality of two Infra* wrappers via their diffusion diagrams (vertex -> total-occurrence multisets). Returns False on head mismatch. Option Method (\"Diffuse\" (default; |A cap B| > |A delta B|, equivalently weighted Jaccard > 1/2) | \"Overlap\" (at least one common vertex) | \"Set\" (vertex sets identical) | \"Multiset\" (diffusion diagrams identical)).";
